const searchData = [
  {
    "title": "सीएसआईआर-नेशनल बॉटनिकल रिसर्च इंस्टीट्यूट (सीएसआईआर-एनबीआरआई), लखनऊ में डायरेक्टर के पद के लिए विज्ञापन [अंतिम तिथि: 15/09/2026]",
    "url": "/generated/posts/last-date-15-09-2026.html",
    "category": "Recruitment",
    "department": "Government",
    "description": "सीएसआईआर-नेशनल बॉटनिकल रिसर्च इंस्टीट्यूट (सीएसआईआर-एनबीआरआई), लखनऊ में डायरेक्टर के पद के लिए विज्ञापन [अंतिम तिथि: 15/09/2026] | Council of Scientific & Industrial Research पेंशनर्स कॉर्नर कर्मचारी कॉर्नर स्क्रीन रीडर एक्सेस मुख्य सामग्री पर जाएं A- A A+ A A खोज साइट मैप English Hindi वैज्ञानिक तथ",
    "keywords": [
      "15092026",
      "2026",
      "government",
      "jobs",
      "latest"
    ]
  },
  {
    "title": "Walk-in-interview for the Post of Field Attendant",
    "url": "/generated/posts/walk-in-interview-for-the-post-of-field-attendant.html",
    "category": "Recruitment",
    "department": "Agriculture",
    "description": "Sardar Vallabhbhai Patel University of Agriculture & Technology",
    "keywords": [
      "attendant",
      "field",
      "for",
      "government",
      "jobs",
      "latest",
      "post",
      "the",
      "walkininterview"
    ]
  },
  {
    "title": "Walk In-interview for Junior Research Fellow",
    "url": "/generated/posts/walk-in-interview-for-junior-research-fellow.html",
    "category": "Recruitment",
    "department": "Agriculture",
    "description": "Sardar Vallabhbhai Patel University of Agriculture & Technology",
    "keywords": [
      "fellow",
      "for",
      "government",
      "ininterview",
      "jobs",
      "junior",
      "latest",
      "research",
      "walk"
    ]
  },
  {
    "title": "WALK IN INTERVIEW for selection of Young Professional-I (YP-I), at ICAR,CIFE Mumbai",
    "url": "/generated/posts/walk-in-interview-for-selection-of-young-professional-i-yp-i-at-icar-cife-mumbai.html",
    "category": "Recruitment",
    "department": "ICAR",
    "description": "WALK IN INTERVIEW for selection of Young Professional-I (YP-I), at ICAR,CIFE Mumbai | Official website of ICAR-Central Institute of Fisheries Education, Mumbai Like on Facebook Follow on X Subscribe on Youtube Follow on Instagram Connect on LinkedIn भारत सरकार | Government of India Opens in a new wi",
    "keywords": [
      "for",
      "government",
      "icarcife",
      "interview",
      "jobs",
      "latest",
      "mumbai",
      "professionali",
      "selection",
      "walk",
      "young",
      "ypi"
    ]
  },
  {
    "title": "Result of University Entrance Test (UET-UG) – 2026",
    "url": "/generated/posts/result-of-university-entrance-test-uet-ug-2026.html",
    "category": "Result",
    "department": "Government",
    "description": "Admission Portal - SKUAST-Kashmir IUMS Admissions How it Works Programmes Sign In Form Filling Tutorial Important Facing difficulty in filling the application form? Watch the Step-by-Step Official Tutorial Video for Undergraduate (UG) Admissions! Watch Video Registrar's Advisory Kickstart your futur",
    "keywords": [
      "2026",
      "entrance",
      "government",
      "result",
      "test",
      "uetug",
      "university"
    ]
  },
  {
    "title": "TERM END EXAMINATION- AUGUST 2026 TIME TABLE",
    "url": "/generated/posts/term-end-examination-august-2026-time-table.html",
    "category": "Exam",
    "department": "Government",
    "description": "Tamil Nadu Open University A- A A+ Screen Reader தமிழ் R G B தமிழ்நாடு திறந்தநிலைப் பல்கலைக்கழகம் எல்லோருக்கும் எப்போதும் கல்வி Tamil Nadu Open University Education for All and Ever NAAC 'A+' Grade with CGPA 3.32 (Cycle - 1) (A State Open University established by the Tamil Nadu Government , Recogni",
    "keywords": [
      "2026",
      "august",
      "end",
      "examination",
      "government",
      "jobs",
      "latest",
      "table",
      "term",
      "time"
    ]
  },
  {
    "title": "TERM END EXAMINATION AUGUST 2026 - Notification",
    "url": "/generated/posts/term-end-examination-august-2026-notification.html",
    "category": "Exam",
    "department": "Government",
    "description": "",
    "keywords": [
      "2026",
      "august",
      "end",
      "examination",
      "government",
      "notification",
      "recruitment",
      "term"
    ]
  },
  {
    "title": "RESULT Dated 23-07-2026: Marks obtained by the candidates in the Driving Test followed by Viva Voce for recruitment to the posts of Driver in the establishments of the District & Subordinate Judiciary of Tripura in pursuance of the Advertisement No. DC 01/2025, dated 23.05.2025.",
    "url": "/generated/posts/result-dated-23-07-2026-marks-obtained-by-the-candidates-in-the-driving-test-followed-by-viva-voce-for-recruitment-to-the-posts-of-driv-dea9c6e48c.html",
    "category": "Result",
    "department": "Government",
    "description": "Official Notification PDF Available.",
    "keywords": [
      "012025",
      "2026",
      "23052025",
      "23072026",
      "advertisement",
      "candidates",
      "dated",
      "district",
      "driver",
      "driving",
      "establishments",
      "followed",
      "for",
      "government",
      "judiciary",
      "marks",
      "obtained",
      "posts",
      "pursuance",
      "recruitment",
      "result",
      "subordinate",
      "test",
      "the",
      "tripura",
      "viva",
      "voce"
    ]
  },
  {
    "title": "Recruitment of PROJECT ENGINEERS vide Advt.2026-1 through walk-in interview in BENGALURU on 06th & 07th June 2026",
    "url": "/generated/posts/recruitment-of-project-engineers-vide-advt-2026-1-through-walk-in-interview-in-bengaluru-on-06th-and-07th-june-2026.html",
    "category": "Recruitment",
    "department": "Defence",
    "description": "Recruitment of PROJECT ENGINEERS vide Advt.2026-1 through walk-in interview in BENGALURU on 06th & 07th June 2026 | Official Website of Bharat Dynamics Limited (BDL) under the Ministry of Defence, Government of India. Top Menu Skip to main content Screen Reader Access A+ A A- A A A हिंदी भारत सरकार",
    "keywords": [
      "06th",
      "07th",
      "2026",
      "advt20261",
      "bengaluru",
      "engineers",
      "government",
      "interview",
      "june",
      "project",
      "recruitment",
      "through",
      "vide",
      "walkin"
    ]
  },
  {
    "title": "Online Application for the Post of Subject Matter Specialist (SMS) in Different Krishi Vigyan Kendras (KVKs) of SKUAST-K",
    "url": "/generated/posts/online-application-for-the-post-of-subject-matter-specialist-sms-in-different-krishi-vigyan-kendras-kvks-of-skuast-k.html",
    "category": "Recruitment",
    "department": "Agriculture",
    "description": "Recruitment Portal | Subject Matter Specialist (SMS) | SKUAST-Kashmir Online applications closed on 22 Jul 2026, 11:59 PM. Sher-i-Kashmir University of Agricultural Sciences & Technology of Kashmir Technical Support: +91 7298054925 Download Notice Sign in to your Account ! 3rd Best State Agri. Uni 7",
    "keywords": [
      "application",
      "banking",
      "different",
      "for",
      "jobs",
      "kendras",
      "krishi",
      "kvks",
      "latest",
      "matter",
      "online",
      "post",
      "skuastk",
      "sms",
      "specialist",
      "subject",
      "the",
      "vigyan"
    ]
  },
  {
    "title": "Notification regarding the appointment of a Part-Time Physician Doctor at ICAR CIFE, Mumbai",
    "url": "/generated/posts/notification-regarding-the-appointment-of-a-part-time-physician-doctor-at-icar-cife-mumbai.html",
    "category": "Recruitment",
    "department": "ICAR",
    "description": "Notification regarding the appointment of a Part-Time Physician Doctor at ICAR CIFE, Mumbai | Official website of ICAR-Central Institute of Fisheries Education, Mumbai Like on Facebook Follow on X Subscribe on Youtube Follow on Instagram Connect on LinkedIn भारत सरकार | Government of India Opens in",
    "keywords": [
      "appointment",
      "cife",
      "doctor",
      "icar",
      "medical",
      "mumbai",
      "notification",
      "parttime",
      "physician",
      "recruitment",
      "regarding",
      "the"
    ]
  },
  {
    "title": "Notification regarding the appointment of a Part-Time Physician Doctor at ICAR CIFE, Mumbai",
    "url": "/generated/posts/notification-regarding-the-appointment-of-a-part-time-physician-doctor-at-icar-cife-mumbai-08bfa205ec.html",
    "category": "Recruitment",
    "department": "ICAR",
    "description": "Notification regarding the appointment of a Part-Time Physician Doctor at ICAR CIFE, Mumbai | Official website of ICAR-Central Institute of Fisheries Education, Mumbai Like on Facebook Follow on X Subscribe on Youtube Follow on Instagram Connect on LinkedIn भारत सरकार | Government of India Opens in",
    "keywords": [
      "appointment",
      "cife",
      "doctor",
      "icar",
      "medical",
      "mumbai",
      "notification",
      "parttime",
      "physician",
      "recruitment",
      "regarding",
      "the"
    ]
  },
  {
    "title": "Notification of walk in interviews for engagement to purely temporary and contractual positions of Young Professional-I & Young Professional-II at ICAR-NDRI Karnal.",
    "url": "/generated/posts/notification-of-walk-in-interviews-for-engagement-to-purely-temporary-and-contractual-positions-of-young-professional-i-and-young-professional-ii-at-icar-ndri-karnal.html",
    "category": "Recruitment",
    "department": "ICAR",
    "description": "Notification of walk in interviews for engagement to purely temporary and contractual positions of Young Professional-I & Young Professional-II at ICAR-NDRI Karnal. | Official Website of ICAR-National Dairy Research Institute, Karnal (India) भारत सरकार |\n                Government of India Skip to m",
    "keywords": [
      "and",
      "contractual",
      "engagement",
      "for",
      "government",
      "icarndri",
      "interviews",
      "karnal",
      "notification",
      "positions",
      "professionali",
      "professionalii",
      "purely",
      "recruitment",
      "temporary",
      "walk",
      "young"
    ]
  },
  {
    "title": "Notification of walk in interviews for engagement to purely temporary and contractual positions of Research Associate, Senior Research Fellow, Young Professional-I & Young Professional-II at ICAR-NDRI Karnal.",
    "url": "/generated/posts/notification-of-walk-in-interviews-for-engagement-to-purely-temporary-and-contractual-positions-of-research-associate-senior-research-fellow-young-professional-i-and-young-professional-ii-at-icar-ndri-karnal.html",
    "category": "Recruitment",
    "department": "ICAR",
    "description": "Notification of walk in interviews for engagement to purely temporary and contractual positions of Research Associate, Senior Research Fellow, Young Professional-I & Young Professional-II at ICAR-NDRI Karnal. | Official Website of ICAR-National Dairy Research Institute, Karnal (India) भारत सरकार |",
    "keywords": [
      "and",
      "associate",
      "contractual",
      "engagement",
      "fellow",
      "for",
      "government",
      "icarndri",
      "interviews",
      "karnal",
      "notification",
      "positions",
      "professionali",
      "professionalii",
      "purely",
      "recruitment",
      "research",
      "senior",
      "temporary",
      "walk",
      "young"
    ]
  },
  {
    "title": "NOTIFICATION Dated 30-06-2026: List of Qualified Candidates (Driving Test held w.e.f. 28.05.2026 to 12.06.2026) for recruitment to the posts of Driver for the establishments of the District & Subordinate Judiciary of Tripura in pursuance of the Advertisement No. DC 01/2025, dated 23.05.2025.",
    "url": "/generated/posts/notification-dated-30-06-2026-list-of-qualified-candidates-driving-test-held-w-e-f-28-05-2026-to-12-06-2026-for-recruitment-to-the-post-a9bdc5ec59.html",
    "category": "Result",
    "department": "Government",
    "description": "Official Notification PDF Available.",
    "keywords": [
      "012025",
      "12062026",
      "2026",
      "23052025",
      "28052026",
      "30062026",
      "advertisement",
      "candidates",
      "dated",
      "district",
      "driver",
      "driving",
      "establishments",
      "for",
      "government",
      "held",
      "judiciary",
      "list",
      "notification",
      "posts",
      "pursuance",
      "qualified",
      "recruitment",
      "subordinate",
      "test",
      "the",
      "tripura",
      "wef"
    ]
  },
  {
    "title": "NOTIFICATION Dated 29-06-2026: Limited Departmental Competitive Examination (LDCE) for filling up 02(two) vacancies in Grade-I of the Tripura Judicial Service.",
    "url": "/generated/posts/notification-dated-29-06-2026-limited-departmental-competitive-examination-ldce-for-filling-up-02-two-vacancies-in-grade-i-of-the-tripura-judicial-service.html",
    "category": "Recruitment",
    "department": "Government",
    "description": "Official Notification PDF Available.",
    "keywords": [
      "02two",
      "2026",
      "29062026",
      "competitive",
      "dated",
      "departmental",
      "examination",
      "filling",
      "for",
      "government",
      "gradei",
      "judicial",
      "ldce",
      "limited",
      "notification",
      "recruitment",
      "service",
      "the",
      "tripura",
      "vacancies"
    ]
  },
  {
    "title": "NOTIFICATION Dated 25-07-2026: Online applications are invited for filling up of the following 04(four) vacant post of System Assistant under e-Courts Services.",
    "url": "/generated/posts/notification-dated-25-07-2026-online-applications-are-invited-for-filling-up-of-the-following-04-four-vacant-post-of-system-assistant-under-e-courts-services.html",
    "category": "Recruitment",
    "department": "Banking",
    "description": "Official Notification PDF Available.",
    "keywords": [
      "04four",
      "2026",
      "25072026",
      "applications",
      "are",
      "assistant",
      "banking",
      "dated",
      "ecourts",
      "filling",
      "following",
      "for",
      "invited",
      "notification",
      "online",
      "post",
      "recruitment",
      "services",
      "system",
      "the",
      "under",
      "vacant"
    ]
  },
  {
    "title": "NOTIFICATION Dated 20.06.2026: Online applications are invited from the eligible Advocates and Judicial Officers for filling up of 01(one) vacancy in Grade-I of Tripura Judicial Service.",
    "url": "/generated/posts/notification-dated-20-06-2026-online-applications-are-invited-from-the-eligible-advocates-and-judicial-officers-for-filling-up-of-01-one-vacancy-in-grade-i-of-tripura-judicial-service.html",
    "category": "Recruitment",
    "department": "Banking",
    "description": "Official Notification PDF Available.",
    "keywords": [
      "01one",
      "20062026",
      "2026",
      "advocates",
      "and",
      "applications",
      "are",
      "banking",
      "dated",
      "eligible",
      "filling",
      "for",
      "from",
      "gradei",
      "invited",
      "judicial",
      "notification",
      "officers",
      "online",
      "recruitment",
      "service",
      "the",
      "tripura",
      "vacancy"
    ]
  },
  {
    "title": "NOTIFICATION Dated 15-05-2026: Written Test for recruitment to the posts of Lower Division Clerk for the establishments of the District & Subordinate Judiciary of Tripura (Advn. No. DC 01/2025, dated 23.05.2025), will be held on 28.06.2026 (Sunday).",
    "url": "/generated/posts/notification-dated-15-05-2026-written-test-for-recruitment-to-the-posts-of-lower-division-clerk-for-the-establishments-of-the-district-and-subordinate-judiciary-of-tripura-advn-no-dc-01-2025-dated-23-05-2025-will-be-held-on-28-06-2026-sunday.html",
    "category": "Recruitment",
    "department": "Government",
    "description": "Official Notification PDF Available.",
    "keywords": [
      "012025",
      "15052026",
      "2026",
      "23052025",
      "28062026",
      "advn",
      "clerk",
      "dated",
      "district",
      "division",
      "establishments",
      "for",
      "government",
      "held",
      "judiciary",
      "lower",
      "notification",
      "posts",
      "recruitment",
      "subordinate",
      "sunday",
      "test",
      "the",
      "tripura",
      "will",
      "written"
    ]
  },
  {
    "title": "NOTIFICATION Dated 11-05-2026: Online applications are hereby invited for appointment to 05 (five) vacant posts of Junior Grade Translator in the establishment of the High Court of Tripura.",
    "url": "/generated/posts/notification-dated-11-05-2026-online-applications-are-hereby-invited-for-appointment-to-05-five-vacant-posts-of-junior-grade-translator-in-the-establishment-of-the-high-court-of-tripura.html",
    "category": "Recruitment",
    "department": "Banking",
    "description": "Official Notification PDF Available.",
    "keywords": [
      "11052026",
      "2026",
      "applications",
      "appointment",
      "are",
      "banking",
      "court",
      "dated",
      "establishment",
      "five",
      "for",
      "grade",
      "hereby",
      "high",
      "invited",
      "junior",
      "notification",
      "online",
      "posts",
      "recruitment",
      "the",
      "translator",
      "tripura",
      "vacant"
    ]
  },
  {
    "title": "Notice: Use this link to download your e-Admit Card for Driving Efficiency Test (DET) to be conducted for the post of Bihar Police Driver Constable .",
    "url": "/generated/posts/notice-use-this-link-to-download-your-e-admit-card-for-driving-efficiency-test-det-to-be-conducted-for-the-post-of-bihar-police-driver-constable.html",
    "category": "Admit Card",
    "department": "Police",
    "description": "",
    "keywords": [
      "admit",
      "banking",
      "bihar",
      "card",
      "conducted",
      "constable",
      "det",
      "download",
      "driver",
      "driving",
      "eadmit",
      "efficiency",
      "for",
      "link",
      "notice",
      "police",
      "post",
      "test",
      "the",
      "this",
      "use",
      "your"
    ]
  },
  {
    "title": "Notice: Apply Online for the post of Constables for Bihar Police, Bihar Special Armed Police and other units.",
    "url": "/generated/posts/notice-apply-online-for-the-post-of-constables-for-bihar-police-bihar-special-armed-police-and-other-units.html",
    "category": "Recruitment",
    "department": "Police",
    "description": "",
    "keywords": [
      "and",
      "apply",
      "armed",
      "banking",
      "bihar",
      "constables",
      "for",
      "jobs",
      "latest",
      "notice",
      "online",
      "other",
      "police",
      "post",
      "special",
      "the",
      "units"
    ]
  },
  {
    "title": "Notice regarding Computer Operator-cum-Typist Recruitment Examination, 2026",
    "url": "/generated/posts/notice-regarding-computer-operator-cum-typist-recruitment-examination-2026.html",
    "category": "Exam",
    "department": "Government",
    "description": "",
    "keywords": [
      "2026",
      "computer",
      "examination",
      "government",
      "notice",
      "operatorcumtypist",
      "recruitment",
      "regarding"
    ]
  },
  {
    "title": "List of provisionally Selected Candidate(s) for the posts of Project Engineer(s) on contract basis vide Advt 2026-1",
    "url": "/generated/posts/list-of-provisionally-selected-candidate-s-for-the-posts-of-project-engineer-s-on-contract-basis-vide-advt-2026-1.html",
    "category": "Result",
    "department": "Defence",
    "description": "List of provisionally Selected Candidate(s) for the posts of Project Engineer(s) on contract basis vide Advt 2026-1 | Official Website of Bharat Dynamics Limited (BDL) under the Ministry of Defence, Government of India. Top Menu Skip to main content Screen Reader Access A+ A A- A A A हिंदी भारत सरका",
    "keywords": [
      "2026",
      "20261",
      "advt",
      "basis",
      "candidates",
      "contract",
      "engineers",
      "for",
      "government",
      "jobs",
      "latest",
      "list",
      "posts",
      "project",
      "provisionally",
      "selected",
      "the",
      "vide"
    ]
  },
  {
    "title": "Link to apply for Ex-Cadre Assistant Recruitment Examination, 2026 (Advertisement No. PHC/03/2026)",
    "url": "/generated/posts/link-to-apply-for-ex-cadre-assistant-recruitment-examination-2026-advertisement-no-phc-03-2026.html",
    "category": "Recruitment",
    "department": "Government",
    "description": "",
    "keywords": [
      "2026",
      "advertisement",
      "apply",
      "assistant",
      "examination",
      "excadre",
      "for",
      "government",
      "link",
      "phc032026",
      "recruitment"
    ]
  },
  {
    "title": "Individual score for the post of Associate Professor/Sr. Scientist",
    "url": "/generated/posts/individual-score-for-the-post-of-associate-professor-sr-scientist.html",
    "category": "Recruitment",
    "department": "Teaching",
    "description": "University Recruitment Portal | SKUAST-Kashmir Sher-E-Kashmir University of Agricultural Sciences & Technology of Kashmir Main Campus, Shalimar, Srinagar - 190025 University Recruitment Portal 3rd Best State Agriculture University • 7th Rank in Agriculture (NIRF) • 36th State Public University • 75t",
    "keywords": [
      "associate",
      "for",
      "individual",
      "jobs",
      "latest",
      "post",
      "professorsr",
      "scientist",
      "score",
      "teaching",
      "the"
    ]
  },
  {
    "title": "Important Notice: Download your e-Admit Card for PET of Bihar Police Driver Constable.",
    "url": "/generated/posts/important-notice-download-your-e-admit-card-for-pet-of-bihar-police-driver-constable.html",
    "category": "Admit Card",
    "department": "Police",
    "description": "",
    "keywords": [
      "admit",
      "banking",
      "bihar",
      "card",
      "constable",
      "download",
      "driver",
      "eadmit",
      "for",
      "important",
      "notice",
      "pet",
      "police",
      "your"
    ]
  },
  {
    "title": "Important Notice: Download your e-Admit Card for PET of Bihar Police Constable.",
    "url": "/generated/posts/important-notice-download-your-e-admit-card-for-pet-of-bihar-police-constable.html",
    "category": "Admit Card",
    "department": "Police",
    "description": "",
    "keywords": [
      "admit",
      "banking",
      "bihar",
      "card",
      "constable",
      "download",
      "eadmit",
      "for",
      "important",
      "notice",
      "pet",
      "police",
      "your"
    ]
  },
  {
    "title": "Important Notice: Download Admit Card for PET of Bihar Police Constable",
    "url": "/generated/posts/important-notice-download-admit-card-for-pet-of-bihar-police-constable.html",
    "category": "Admit Card",
    "department": "Police",
    "description": "",
    "keywords": [
      "admit",
      "banking",
      "bihar",
      "card",
      "constable",
      "download",
      "for",
      "important",
      "notice",
      "pet",
      "police"
    ]
  },
  {
    "title": "Important Notice: Apply Online for the Post of Driver Constables in Bihar Police and Bihar Special Armed Police.",
    "url": "/generated/posts/important-notice-apply-online-for-the-post-of-driver-constables-in-bihar-police-and-bihar-special-armed-police.html",
    "category": "Recruitment",
    "department": "Police",
    "description": "",
    "keywords": [
      "and",
      "apply",
      "armed",
      "banking",
      "bihar",
      "constables",
      "driver",
      "for",
      "important",
      "jobs",
      "latest",
      "notice",
      "online",
      "police",
      "post",
      "special",
      "the"
    ]
  },
  {
    "title": "Important Notice: Apply Online for the Post of Constables for Bihar Police and Bihar Special Armed Police.",
    "url": "/generated/posts/important-notice-apply-online-for-the-post-of-constables-for-bihar-police-and-bihar-special-armed-police.html",
    "category": "Recruitment",
    "department": "Police",
    "description": "",
    "keywords": [
      "and",
      "apply",
      "armed",
      "banking",
      "bihar",
      "constables",
      "for",
      "important",
      "jobs",
      "latest",
      "notice",
      "online",
      "police",
      "post",
      "special",
      "the"
    ]
  },
  {
    "title": "Important Notice: Apply Online for the Post of Constables (General Duty Close Cadre) in Special Branch of Bihar Police.",
    "url": "/generated/posts/important-notice-apply-online-for-the-post-of-constables-general-duty-close-cadre-in-special-branch-of-bihar-police.html",
    "category": "Recruitment",
    "department": "Police",
    "description": "",
    "keywords": [
      "apply",
      "banking",
      "bihar",
      "branch",
      "cadre",
      "close",
      "constables",
      "duty",
      "for",
      "general",
      "important",
      "jobs",
      "latest",
      "notice",
      "online",
      "police",
      "post",
      "special",
      "the"
    ]
  },
  {
    "title": "Important Notice: Apply Online for the Post of Constable (Operator) in Bihar Police.",
    "url": "/generated/posts/important-notice-apply-online-for-the-post-of-constable-operator-in-bihar-police.html",
    "category": "Recruitment",
    "department": "Police",
    "description": "",
    "keywords": [
      "apply",
      "banking",
      "bihar",
      "constable",
      "for",
      "important",
      "jobs",
      "latest",
      "notice",
      "online",
      "operator",
      "police",
      "post",
      "the"
    ]
  },
  {
    "title": "Final Scorecard and Portal Access for Professor/Chief Scientist",
    "url": "/generated/posts/final-scorecard-and-portal-access-for-professor-chief-scientist.html",
    "category": "Result",
    "department": "Teaching",
    "description": "Recruitment Portal | Professor-cum-Chief Scientist | SKUAST-Kashmir Sher-E-Kashmir University of Agricultural Sciences & Technology of Kashmir Download Notice Sign in to your Account ! 3rd Best State Agri. Uni 7th NIRF Agri & Allied 36th State Public Univ. 75th University Category 94th Overall Categ",
    "keywords": [
      "access",
      "and",
      "final",
      "for",
      "jobs",
      "latest",
      "portal",
      "professorchief",
      "scientist",
      "scorecard",
      "teaching"
    ]
  },
  {
    "title": "Final Scorecard and Portal Access for Officer Recruitment",
    "url": "/generated/posts/final-scorecard-and-portal-access-for-officer-recruitment.html",
    "category": "Result",
    "department": "Agriculture",
    "description": "Officers Recruitment Portal 2026 | SKUAST-Kashmir Sher-e-Kashmir University of Agricultural Sciences & Technology of Kashmir Main Campus, Shalimar, Srinagar - 190025 Login / View Score Advt Notice No. 02 of 2026 Dated: 24.02.2026 Official Recruitment Portal for Officers of the University Online appl",
    "keywords": [
      "access",
      "and",
      "final",
      "for",
      "government",
      "officer",
      "portal",
      "recruitment",
      "scorecard"
    ]
  },
  {
    "title": "Exam Time Table",
    "url": "/generated/posts/exam-time-table.html",
    "category": "Exam",
    "department": "Government",
    "description": "Tamil Nadu Open University A- A A+ Screen Reader தமிழ் R G B தமிழ்நாடு திறந்தநிலைப் பல்கலைக்கழகம் எல்லோருக்கும் எப்போதும் கல்வி Tamil Nadu Open University Education for All and Ever NAAC 'A+' Grade with CGPA 3.32 (Cycle - 1) (A State Open University established by the Tamil Nadu Government , Recogni",
    "keywords": [
      "exam",
      "government",
      "jobs",
      "latest",
      "table",
      "time"
    ]
  },
  {
    "title": "ENTRANCE EXAMINATION RESULT 2026 FOR all UG/PG/Ph.D. programmes",
    "url": "/generated/posts/entrance-examination-result-2026-for-all-ug-pg-ph-d-programmes.html",
    "category": "Result",
    "department": "Agriculture",
    "description": "PRINT. GOVIND BALLABH PANT UNIVERSITY OF AGRICULTURE & TECHNOLOGY (Pantnagar, U.S. Nagar, Uttarakhand) Home Candidate Login for Counselling Sponsored MASTERS/M.Tech/Ph.D./Admission to the Second/Third Year for UG programmes under NEP2020 login ☰ Select your programme: Please Select UG MASTERS' MCA P",
    "keywords": [
      "2026",
      "all",
      "entrance",
      "examination",
      "for",
      "government",
      "programmes",
      "result",
      "ugpgphd"
    ]
  },
  {
    "title": "Apply for Faculty Positions",
    "url": "/generated/posts/apply-for-faculty-positions.html",
    "category": "Recruitment",
    "department": "Teaching",
    "description": "IISc Faculty Login Indian Institute of Science, Bangalore Faculty Recruitment Portal Sign In New applicant? Register here Forgot Password?",
    "keywords": [
      "apply",
      "faculty",
      "for",
      "jobs",
      "latest",
      "positions",
      "teaching"
    ]
  },
  {
    "title": "Agri. Scientists Recruitment Board",
    "url": "/generated/posts/agri-scientists-recruitment-board.html",
    "category": "Recruitment",
    "department": "Government",
    "description": "",
    "keywords": [
      "agri",
      "board",
      "government",
      "recruitment",
      "scientists"
    ]
  },
  {
    "title": "Advertisement regarding Ex-Cadre Assistant Recruitment Examination, 2026",
    "url": "/generated/posts/advertisement-regarding-ex-cadre-assistant-recruitment-examination-2026.html",
    "category": "Recruitment",
    "department": "Government",
    "description": "",
    "keywords": [
      "2026",
      "advertisement",
      "assistant",
      "examination",
      "excadre",
      "government",
      "recruitment",
      "regarding"
    ]
  },
  {
    "title": "Advertisement of Young Professional-1 at ICAR-NDRI, ERS, Kalyani.",
    "url": "/generated/posts/advertisement-of-young-professional-1-at-icar-ndri-ers-kalyani.html",
    "category": "Recruitment",
    "department": "ICAR",
    "description": "Advertisement of Young Professional-1 at ICAR-NDRI, ERS, Kalyani. | Official Website of ICAR-National Dairy Research Institute, Karnal (India) भारत सरकार |\n                Government of India Skip to main content Screen Reader Access A+ A A- A A A हिंदी Weather Forecast Online Payment Home About Us",
    "keywords": [
      "advertisement",
      "ers",
      "government",
      "icarndri",
      "jobs",
      "kalyani",
      "latest",
      "professional1",
      "young"
    ]
  },
  {
    "title": "Advertisement for the posts of GUEST FACULTY in College Of Horticulture, Bharsar",
    "url": "/generated/posts/advertisement-for-the-posts-of-guest-faculty-in-college-of-horticulture-bharsar.html",
    "category": "Recruitment",
    "department": "Teaching",
    "description": "One moment, please... Loader Please wait while your request is being verified...",
    "keywords": [
      "advertisement",
      "bharsar",
      "college",
      "faculty",
      "for",
      "guest",
      "horticulture",
      "jobs",
      "latest",
      "posts",
      "teaching",
      "the"
    ]
  },
  {
    "title": "Advertisement for the post of Young Professional - II ICAR-CIFE, Mumbai",
    "url": "/generated/posts/advertisement-for-the-post-of-young-professional-ii-icar-cife-mumbai.html",
    "category": "Recruitment",
    "department": "ICAR",
    "description": "Advertisement for the post of Young Professional - II ICAR-CIFE, Mumbai | Official website of ICAR-Central Institute of Fisheries Education, Mumbai Like on Facebook Follow on X Subscribe on Youtube Follow on Instagram Connect on LinkedIn भारत सरकार | Government of India Opens in a new window A+ A A-",
    "keywords": [
      "advertisement",
      "for",
      "government",
      "icarcife",
      "jobs",
      "latest",
      "mumbai",
      "post",
      "professional",
      "the",
      "young"
    ]
  },
  {
    "title": "Advertisement for the post of Young Professional - I ICAR-CIFE, Mumbai",
    "url": "/generated/posts/advertisement-for-the-post-of-young-professional-i-icar-cife-mumbai.html",
    "category": "Recruitment",
    "department": "ICAR",
    "description": "Advertisement for the post of Young Professional - I ICAR-CIFE, Mumbai | Official website of ICAR-Central Institute of Fisheries Education, Mumbai Like on Facebook Follow on X Subscribe on Youtube Follow on Instagram Connect on LinkedIn भारत सरकार | Government of India Opens in a new window A+ A A-",
    "keywords": [
      "advertisement",
      "for",
      "government",
      "icarcife",
      "jobs",
      "latest",
      "mumbai",
      "post",
      "professional",
      "the",
      "young"
    ]
  },
  {
    "title": "Advertisement for the post of Senior Research Fellow (SRF) ICAR-CIFE, Mumbai",
    "url": "/generated/posts/advertisement-for-the-post-of-senior-research-fellow-srf-icar-cife-mumbai.html",
    "category": "Recruitment",
    "department": "ICAR",
    "description": "Advertisement for the post of Senior Research Fellow (SRF) ICAR-CIFE, Mumbai | Official website of ICAR-Central Institute of Fisheries Education, Mumbai Like on Facebook Follow on X Subscribe on Youtube Follow on Instagram Connect on LinkedIn भारत सरकार | Government of India Opens in a new window A+",
    "keywords": [
      "advertisement",
      "fellow",
      "for",
      "government",
      "icarcife",
      "jobs",
      "latest",
      "mumbai",
      "post",
      "research",
      "senior",
      "srf",
      "the"
    ]
  },
  {
    "title": "Advertisement for calling of applications for 12th batch of incubatees to be incubated at Agri-Business Incubation Centre, SKUAST-J ABI FOUNDATION under the PK-RKVY (RKVY-RAFTAAR)",
    "url": "/generated/posts/advertisement-for-calling-of-applications-for-12th-batch-of-incubatees-to-be-incubated-at-agri-business-incubation-centre-skuast-j-abi-foundation-under-the-pk-rkvy-rkvy-raftaar.html",
    "category": "Recruitment",
    "department": "ICAR",
    "description": "Skuast Jammu | English Hindi 𝑺𝒉𝒆𝒓-𝒆-𝑲𝒂𝒔𝒉𝒎𝒊𝒓 𝑼𝒏𝒊𝒗𝒆𝒓𝒔𝒊𝒕𝒚 𝒐𝒇 𝑨𝒈𝒓𝒊𝒄𝒖𝒍𝒕𝒖𝒓𝒂𝒍 𝑺𝒄𝒊𝒆𝒏𝒄𝒆𝒔 𝒂𝒏𝒅 𝑻𝒆𝒄𝒉𝒏𝒐𝒍𝒐𝒈𝒚 𝒐𝒇 𝑱𝒂𝒎𝒎𝒖 ICAR Accreditation : Grade A 23 rd NIRF Rank Counselling of  CET-2026 (UG) Counselling of CET-2026 (PG) Home At a Glance About us Chancellor Pro-Chancellor Governance Vice Chancellor Registrar Off",
    "keywords": [
      "12th",
      "abi",
      "advertisement",
      "agribusiness",
      "applications",
      "banking",
      "batch",
      "calling",
      "centre",
      "for",
      "foundation",
      "incubated",
      "incubatees",
      "incubation",
      "jobs",
      "latest",
      "pkrkvy",
      "rkvyraftaar",
      "skuastj",
      "the",
      "under"
    ]
  },
  {
    "title": "ADVERTISEMENT Dated 17-07-2026: Online applications are invited in prescribed form for filling up of Group-âDâ posts for the establishments of the Family Courts of Tripura (ADVT. NO. FC 01/2026, Dtd. 17-07-2026).",
    "url": "/generated/posts/advertisement-dated-17-07-2026-online-applications-are-invited-in-prescribed-form-for-filling-up-of-group-d-posts-for-the-establishments-of-the-family-courts-of-tripura-advt-no-fc-01-2026-dtd-17-07-2026.html",
    "category": "Recruitment",
    "department": "Banking",
    "description": "Official Notification PDF Available.",
    "keywords": [
      "012026",
      "17072026",
      "2026",
      "advertisement",
      "advt",
      "applications",
      "are",
      "banking",
      "courts",
      "dated",
      "dtd",
      "establishments",
      "family",
      "filling",
      "for",
      "form",
      "groupd",
      "invited",
      "jobs",
      "latest",
      "online",
      "posts",
      "prescribed",
      "the",
      "tripura"
    ]
  },
  {
    "title": "ADVERTISEMENT Dated 07-07-2026: Online applications are invited for filling up of the 14(fourteen) vacant posts of Junior Administrative Assistant in the Registry of High Court of Tripura.",
    "url": "/generated/posts/advertisement-dated-07-07-2026-online-applications-are-invited-for-filling-up-of-the-14-fourteen-vacant-posts-of-junior-administrative-assistant-in-the-registry-of-high-court-of-tripura.html",
    "category": "Recruitment",
    "department": "Banking",
    "description": "Official Notification PDF Available.",
    "keywords": [
      "07072026",
      "14fourteen",
      "2026",
      "administrative",
      "advertisement",
      "applications",
      "are",
      "assistant",
      "banking",
      "court",
      "dated",
      "filling",
      "for",
      "high",
      "invited",
      "jobs",
      "junior",
      "latest",
      "online",
      "posts",
      "registry",
      "the",
      "tripura",
      "vacant"
    ]
  },
  {
    "title": "ADVERTISEMENT Dated 07-07-2026: Online applications are invited for filling up of the 03(three) vacant posts of Senior Computer Assistant in the Registry of High Court of Tripura.",
    "url": "/generated/posts/advertisement-dated-07-07-2026-online-applications-are-invited-for-filling-up-of-the-03-three-vacant-posts-of-senior-computer-assistant-in-the-registry-of-high-court-of-tripura.html",
    "category": "Recruitment",
    "department": "Banking",
    "description": "Official Notification PDF Available.",
    "keywords": [
      "03three",
      "07072026",
      "2026",
      "advertisement",
      "applications",
      "are",
      "assistant",
      "banking",
      "computer",
      "court",
      "dated",
      "filling",
      "for",
      "high",
      "invited",
      "jobs",
      "latest",
      "online",
      "posts",
      "registry",
      "senior",
      "the",
      "tripura",
      "vacant"
    ]
  },
  {
    "title": "Advertisement & Google Form Link for Engagement of “Law Researcher” on Contractual Basis ( No. 295/UHC/Admin.B/XVI-56/2026 Dated: 23.07.2026)",
    "url": "/generated/posts/advertisement-and-google-form-link-for-engagement-of-law-researcher-on-contractual-basis-no-295-uhc-admin-b-xvi-56-2026-dated-23-07-2026.html",
    "category": "Recruitment",
    "department": "Government",
    "description": "Advertisement & Google Form Link for Engagement of “Law Researcher” on Contractual Basis ( No. 295/UHC/Admin.B/XVI-56/2026 Dated: 23.07.2026) | High Court of Uttarakhand | India Search Search Accessibility Tools Accessibility Tools Color Contrast High Contrast Normal Contrast Highlight Links Invert",
    "keywords": [
      "2026",
      "23072026",
      "295uhcadminbxvi562026",
      "advertisement",
      "basis",
      "contractual",
      "dated",
      "engagement",
      "for",
      "form",
      "google",
      "government",
      "jobs",
      "latest",
      "law",
      "link",
      "researcher"
    ]
  },
  {
    "title": "7 Link for downloading Hall-Ticket for recruitment to the posts in the A.P. High Court Service vide Notification No.01/2026/Estt., dated 20.03...",
    "url": "/generated/posts/7-link-for-downloading-hall-ticket-for-recruitment-to-the-posts-in-the-a-p-high-court-service-vide-notification-no-01-2026-estt-dated-20-03.html",
    "category": "Admit Card",
    "department": "Government",
    "description": "High Court of Andhra Pradesh Tuesday, 2026-08-11, High Contrast Highlight Links Invert Saturation Font Increase A Normal Font Font Decrease Text Spacing Menu Home About Us High Court Digitization eFiling Recruitment Infrastructure Profiles CJ & Sitting Judges Administrative Judges Judges Elevated to",
    "keywords": [
      "2003",
      "2026",
      "court",
      "dated",
      "downloading",
      "for",
      "government",
      "hallticket",
      "high",
      "link",
      "no012026estt",
      "notification",
      "posts",
      "recruitment",
      "service",
      "the",
      "vide"
    ]
  },
  {
    "title": "05-Jun-2026 Empanelment of Young Professionals as 'Legal Research Consultants' on a contract basis, in the National Human Rights Commission (Vacancies)",
    "url": "/generated/posts/05-jun-2026-empanelment-of-young-professionals-as-legal-research-consultants-on-a-contract-basis-in-the-national-human-rights-commission-vacancies.html",
    "category": "Recruitment",
    "department": "Government",
    "description": "NHRC National Human Rights Commission, India (Established under the Protection of Human Rights Act, 1993) Protecting & Promoting Life, Liberty, Equality and Dignity of all Accessibility Tool Navigation Adjustment Screenreader Color Adjustment Light Dark Text Size Increase Reset Decrease Increase Lin",
    "keywords": [
      "05jun2026",
      "2026",
      "basis",
      "commission",
      "consultants",
      "contract",
      "empanelment",
      "government",
      "human",
      "jobs",
      "latest",
      "legal",
      "national",
      "professionals",
      "research",
      "rights",
      "the",
      "vacancies",
      "young"
    ]
  },
  {
    "title": "23 Jul 2026 Applications are invited from the eligible candidates to fill up the following existing/anticipated vacancies on deputation basis in the National Human Rights Commission (Deputation Vacancy Notice No. 07/2026)",
    "url": "/generated/posts/23-jul-2026-applications-are-invited-from-the-eligible-candidates-to-fill-up-the-following-existing-anticipated-vacancies-on-deputation-basis-in-the-national-human-rights-commission-deputation-vacancy-notice-no-07-2026.html",
    "category": "Recruitment",
    "department": "Banking",
    "description": "NHRC National Human Rights Commission, India (Established under the Protection of Human Rights Act, 1993) Protecting & Promoting Life, Liberty, Equality and Dignity of all Accessibility Tool Navigation Adjustment Screenreader Color Adjustment Light Dark Text Size Increase Reset Decrease Increase Lin",
    "keywords": [
      "072026",
      "2026",
      "applications",
      "are",
      "banking",
      "basis",
      "candidates",
      "commission",
      "deputation",
      "eligible",
      "existinganticipated",
      "fill",
      "following",
      "from",
      "human",
      "invited",
      "jul",
      "national",
      "notice",
      "recruitment",
      "rights",
      "the",
      "vacancies",
      "vacancy"
    ]
  },
  {
    "title": "पदनाम लेखाकार/सहायक लेखाकार/कार्यालय सहायक तृतीय/कैशियर कम सहायक लेखाकार के ऑनलाइन आवेदनहेतु क्लिक करें",
    "url": "/generated/posts/online-application.html",
    "category": "Recruitment",
    "department": "Government",
    "description": "",
    "keywords": [
      "government",
      "jobs",
      "latest"
    ]
  },
  {
    "title": "परीक्षा कार्यक्रम New",
    "url": "/generated/posts/exam-new.html",
    "category": "Exam",
    "department": "Government",
    "description": "परीक्षा कार्यक्रम(UPDATED EXAM CALENDAR) | Uttarakhand Subordinate Service Selection Commission | India Search Search Accessibility Tools Accessibility Tools Color Contrast High Contrast Normal Contrast Highlight Links Invert Saturation Text Size Font Size Increase Font Size Decrease Normal Font Tex",
    "keywords": [
      "government",
      "jobs",
      "latest",
      "new"
    ]
  },
  {
    "title": "पदनाम विधि सहायक/शोध अधिकारी/सहायक बोरिंग टेक्नीशियन व अन्य तकनीकी अर्हता से सम्बंधित पाठ्यक्रमहेतु क्लिक करें New",
    "url": "/generated/posts/syllabus-new.html",
    "category": "Syllabus",
    "department": "Government",
    "description": "पदनाम-विधि सहायक/शोध अधिकारी/सहायक बोरिंग टेक्नीशियन व अन्य तकनीकी अर्हता से सम्बंधित पाठ्यक्रम(Syllabus)हेतु क्लिक करें | Uttarakhand Subordinate Service Selection Commission | India Search Search Accessibility Tools Accessibility Tools Color Contrast High Contrast Normal Contrast Highlight Links I",
    "keywords": [
      "government",
      "jobs",
      "latest",
      "new"
    ]
  },
  {
    "title": "पदनाम पशुधन प्रसार अधिकारी के रिक्त पदों पर चयन हेतु विज्ञापन New",
    "url": "/generated/posts/new.html",
    "category": "Recruitment",
    "department": "Government",
    "description": "पदनाम-पशुधन प्रसार अधिकारी के रिक्त पदों पर चयन हेतु विज्ञापन(ADVT.)(Click Here) | Uttarakhand Subordinate Service Selection Commission | India Search Search Accessibility Tools Accessibility Tools Color Contrast High Contrast Normal Contrast Highlight Links Invert Saturation Text Size Font Size Inc",
    "keywords": [
      "government",
      "jobs",
      "latest",
      "new"
    ]
  },
  {
    "title": "पदनाम पटवारी/लेखपाल) की शारीरिक मानक एवं दक्षता परीक्षा के प्रवेश पत्रहेतु क्लिक करें",
    "url": "/generated/posts/exam-admit-card.html",
    "category": "Admit Card",
    "department": "UKSSSC",
    "description": "Uttarakhand Subordinate Service Selection Commission Toggle navigation Menu Home Login For Admit Card Contact Us Login with Email ID and Password Login with Application No. and Date of birth Login with Name, Father's Name and Date of birth Login with Mobile No. and Date of birth © Uttarakhand Subord",
    "keywords": [
      "government",
      "jobs",
      "latest"
    ]
  },
  {
    "title": "RRVUN Common Recruitment of Junior Engineers I & Junior Accountant and Junior Assistant/Commercial Assistant II Registration From 05 Aug 2026",
    "url": "/generated/posts/rrvun-common-recruitment-of-junior-engineers-i-and-junior-accountant-and-junior-assistant-commercial-assistant-ii-registration-from-05-aug-2026.html",
    "category": "Recruitment",
    "department": "IBPS",
    "description": "",
    "keywords": [
      "2026",
      "accountant",
      "and",
      "assistant",
      "assistantcommercial",
      "aug",
      "common",
      "engineers",
      "from",
      "government",
      "junior",
      "recruitment",
      "registration",
      "rrvun"
    ]
  },
  {
    "title": "PNB Recruitment of Local Bank Officer in JMGS I Registration From 20 Jul 2026",
    "url": "/generated/posts/pnb-recruitment-of-local-bank-officer-in-jmgs-i-registration-from-20-jul-2026.html",
    "category": "Recruitment",
    "department": "IBPS",
    "description": "Recruitment of Local Bank Officer in JMGS I Recruitment of Local Bank Officer in JMGS I Important Events Dates Commencement of online registration of application 20/07/2026 Closure of registration of application 16/08/2026 Closure for editing application details 16/08/2026 Last date for printing you",
    "keywords": [
      "2026",
      "bank",
      "banking",
      "from",
      "jmgs",
      "jul",
      "local",
      "officer",
      "pnb",
      "recruitment",
      "registration"
    ]
  },
  {
    "title": "IOB Recruitment of Local Bank Officer in JMGS I Registration From 08 Aug 2026",
    "url": "/generated/posts/iob-recruitment-of-local-bank-officer-in-jmgs-i-registration-from-08-aug-2026.html",
    "category": "Recruitment",
    "department": "IBPS",
    "description": "Recruitment of Local Bank Officer in JMGS - I 2026 - 2027 Recruitment of Local Bank Officer in JMGS - I 2026 - 2027 Important Events Dates Commencement of online registration of application 08/08/2026 Closure of registration of application 24/08/2026 Closure for editing application details 24/08/202",
    "keywords": [
      "2026",
      "aug",
      "bank",
      "banking",
      "from",
      "iob",
      "jmgs",
      "local",
      "officer",
      "recruitment",
      "registration"
    ]
  },
  {
    "title": "GPCB Recruitment of Clerk Registration From 10 Aug 2026",
    "url": "/generated/posts/gpcb-recruitment-of-clerk-registration-from-10-aug-2026.html",
    "category": "Recruitment",
    "department": "IBPS",
    "description": "Recruitment of Clerk Recruitment of Clerk Important Events Dates Commencement of online registration of application 10/08/2026 Closure of registration of application 31/08/2026 Closure for editing application details 31/08/2026 Last date for printing your application 15/09/2026 Online Fee Payment 10",
    "keywords": [
      "2026",
      "aug",
      "clerk",
      "from",
      "government",
      "gpcb",
      "recruitment",
      "registration"
    ]
  },
  {
    "title": "BPCL Recruitment to Non Management Posts Registration From 29 Jul 2026",
    "url": "/generated/posts/bpcl-recruitment-to-non-management-posts-registration-from-29-jul-2026.html",
    "category": "Recruitment",
    "department": "IBPS",
    "description": "Recruitment to Non-Management Posts in BPCL Mumbai Refinery & Kochi Refinery Recruitment to Non-Management Posts in BPCL Mumbai Refinery & Kochi Refinery Important Events Dates Commencement of online registration of application 29/07/2026 Closure of registration of application 19/08/2026 Closure for",
    "keywords": [
      "2026",
      "bpcl",
      "from",
      "government",
      "jul",
      "management",
      "non",
      "posts",
      "recruitment",
      "registration"
    ]
  },
  {
    "title": "AIIMS Recruitment to Various Group A Non Faculty Posts Registration From 08 Aug 2026",
    "url": "/generated/posts/aiims-recruitment-to-various-group-a-non-faculty-posts-registration-from-08-aug-2026.html",
    "category": "Recruitment",
    "department": "AIIMS",
    "description": "Recruitment to Various Group-A Non-Faculty Posts on Direct Recruitment Basis Recruitment to Various Group-A Non-Faculty Posts on Direct Recruitment Basis Important Events Dates Commencement of online registration of application 08/08/2026 Closure of registration of application 07/09/2026 Closure for",
    "keywords": [
      "2026",
      "aiims",
      "aug",
      "faculty",
      "from",
      "group",
      "non",
      "posts",
      "recruitment",
      "registration",
      "teaching",
      "various"
    ]
  },
  {
    "title": "AAI Recruitment of Managers and Junior Executives Registration From 08 Aug 2026",
    "url": "/generated/posts/aai-recruitment-of-managers-and-junior-executives-registration-from-08-aug-2026.html",
    "category": "Recruitment",
    "department": "IBPS",
    "description": "",
    "keywords": [
      "2026",
      "aai",
      "and",
      "aug",
      "executives",
      "from",
      "government",
      "junior",
      "managers",
      "recruitment",
      "registration"
    ]
  },
  {
    "title": "मा० उच्च न्यायालय नैनीताल,उत्तराखण्ड के अंतर्गत पदनाम कनिष्ठ सहायक/आशुलिपिक ग्रेड 1पदों के सापेक्ष ऑनलाइन आवेदन पत्र भरने हेतु क्लिक करें New",
    "url": "/generated/posts/answer-1-online-application-card-new.html",
    "category": "Recruitment",
    "department": "Government",
    "description": "",
    "keywords": [
      "government",
      "jobs",
      "latest",
      "new"
    ]
  },
  {
    "title": "मा० उच्च न्यायालय नैनीताल,उत्तराखण्ड के अंतर्गत पदनाम कनिष्ठ सहायक/आशुलिपिक ग्रेड 1 के पदों के सापेक्ष ऑनलाइन आवेदन पत्र भरने हेतु क्लिक करें",
    "url": "/generated/posts/answer-1-online-application-card.html",
    "category": "Recruitment",
    "department": "Government",
    "description": "",
    "keywords": [
      "government",
      "jobs",
      "latest"
    ]
  },
  {
    "title": "SBI Recruitment of Junior Associates Registration From 11 Aug 2026",
    "url": "/generated/posts/sbi-recruitment-of-junior-associates-registration-from-11-aug-2026.html",
    "category": "Recruitment",
    "department": "IBPS",
    "description": "",
    "keywords": [
      "2026",
      "associates",
      "aug",
      "from",
      "government",
      "junior",
      "recruitment",
      "registration",
      "sbi"
    ]
  },
  {
    "title": "Online Preliminary Exam Call Letter for CRP PO/MT XVI Probationary Officers / Management Trainees",
    "url": "/generated/posts/online-preliminary-exam-call-letter-for-crp-po-mt-xvi-probationary-officers-management-trainees.html",
    "category": "Admit Card",
    "department": "IBPS",
    "description": "",
    "keywords": [
      "call",
      "crp",
      "exam",
      "for",
      "government",
      "jobs",
      "latest",
      "letter",
      "management",
      "officers",
      "online",
      "pomt",
      "preliminary",
      "probationary",
      "trainees",
      "xvi"
    ]
  },
  {
    "title": "Recruitment of Jharkhand Combined Civil Services Examination 2025 Advt.No. 05/2026",
    "url": "/generated/posts/recruitment-of-jharkhand-combined-civil-services-examination-2025-advt-no-05-2026.html",
    "category": "Recruitment",
    "department": "Government",
    "description": "",
    "keywords": [
      "052026",
      "2025",
      "advtno",
      "civil",
      "combined",
      "examination",
      "government",
      "jharkhand",
      "recruitment",
      "services"
    ]
  },
  {
    "title": "Recruitment of Jharkhand Combined Civil Services Examination 2025 Advt.No. 01/2026",
    "url": "/generated/posts/recruitment-of-jharkhand-combined-civil-services-examination-2025-advt-no-01-2026.html",
    "category": "Recruitment",
    "department": "Government",
    "description": "",
    "keywords": [
      "012026",
      "2025",
      "advtno",
      "civil",
      "combined",
      "examination",
      "government",
      "jharkhand",
      "recruitment",
      "services"
    ]
  },
  {
    "title": "Recruitment of Jharkhand Combined Civil Services Examination 2023 Advt.No. 06/2026",
    "url": "/generated/posts/recruitment-of-jharkhand-combined-civil-services-examination-2023-advt-no-06-2026.html",
    "category": "Recruitment",
    "department": "Government",
    "description": "",
    "keywords": [
      "062026",
      "2023",
      "advtno",
      "civil",
      "combined",
      "examination",
      "government",
      "jharkhand",
      "recruitment",
      "services"
    ]
  },
  {
    "title": "Recruitment of Assistant Professor in Medical CollegesDepartment Advt.No. 07/2026",
    "url": "/generated/posts/recruitment-of-assistant-professor-in-medical-collegesdepartment-advt-no-07-2026.html",
    "category": "Recruitment",
    "department": "Teaching",
    "description": "",
    "keywords": [
      "072026",
      "2026",
      "advtno",
      "assistant",
      "collegesdepartment",
      "medical",
      "professor",
      "recruitment",
      "teaching"
    ]
  },
  {
    "title": "Recruitment of Assistant Professor in Government Engineering colleges ,Advt.No. 02/2026",
    "url": "/generated/posts/recruitment-of-assistant-professor-in-government-engineering-colleges-advt-no-02-2026.html",
    "category": "Recruitment",
    "department": "Teaching",
    "description": "",
    "keywords": [
      "022026",
      "2026",
      "advtno",
      "assistant",
      "colleges",
      "engineering",
      "government",
      "professor",
      "recruitment",
      "teaching"
    ]
  },
  {
    "title": "Notice regarding recruitment of Jharkhand Combined Civil Services Examination 2025 Advt.No. 01/2026",
    "url": "/generated/posts/notice-regarding-recruitment-of-jharkhand-combined-civil-services-examination-2025-advt-no-01-2026.html",
    "category": "Recruitment",
    "department": "Government",
    "description": "",
    "keywords": [
      "012026",
      "2025",
      "advtno",
      "civil",
      "combined",
      "examination",
      "government",
      "jharkhand",
      "notice",
      "recruitment",
      "regarding",
      "services"
    ]
  },
  {
    "title": "FILL ONLINE DETAILS FOR ADVT. NO.A 6/E 1/2026, LECTURER GOVERNMENT INTER COLLEGE EXAM. 2025.",
    "url": "/generated/posts/fill-online-details-for-advt-no-a-6-e-1-2026-lecturer-government-inter-college-exam-2025.html",
    "category": "Recruitment",
    "department": "Teaching",
    "description": "",
    "keywords": [
      "12026",
      "2025",
      "2026",
      "advt",
      "college",
      "details",
      "exam",
      "fill",
      "for",
      "government",
      "inter",
      "jobs",
      "latest",
      "lecturer",
      "noa",
      "online",
      "teaching"
    ]
  },
  {
    "title": "Corrigendum: Integrated 72nd Combined Competitive Examination – Deletion of 44 Vacancies of Sugarcane Officer.",
    "url": "/generated/posts/corrigendum-integrated-72nd-combined-competitive-examination-deletion-of-44-vacancies-of-sugarcane-officer.html",
    "category": "Recruitment",
    "department": "Government",
    "description": "",
    "keywords": [
      "72nd",
      "combined",
      "competitive",
      "corrigendum",
      "deletion",
      "examination",
      "government",
      "integrated",
      "jobs",
      "latest",
      "officer",
      "sugarcane",
      "vacancies"
    ]
  },
  {
    "title": "24 Oct 2026 CORRIGENDUM NOTICE REGARDING ADVT.NO.D 6/E 1/2025, DIRECTORATE OF HOMOEOPATHY UTTAR PRADESH / HOMOEOPATHIC MEDICAL OFFICER, S 11/32",
    "url": "/generated/posts/24-oct-2026-corrigendum-notice-regarding-advt-no-d-6-e-1-2025-directorate-of-homoeopathy-uttar-pradesh-homoeopathic-medical-officer-s-11-32.html",
    "category": "Recruitment",
    "department": "Medical",
    "description": "",
    "keywords": [
      "1132",
      "12025",
      "2026",
      "advtnod",
      "corrigendum",
      "directorate",
      "homoeopathic",
      "homoeopathy",
      "jobs",
      "latest",
      "medical",
      "notice",
      "oct",
      "officer",
      "pradesh",
      "regarding",
      "uttar"
    ]
  },
  {
    "title": "Recruitment of Lecturer in Govt. Polytechnic/Govt. Women's Polytechnic,Advt.No. 03/2026",
    "url": "/generated/posts/recruitment-of-lecturer-in-govt-polytechnic-govt-women-s-polytechnic-advt-no-03-2026.html",
    "category": "Recruitment",
    "department": "Teaching",
    "description": "",
    "keywords": [
      "032026",
      "2026",
      "govt",
      "lecturer",
      "polytechnicadvtno",
      "polytechnicgovt",
      "recruitment",
      "teaching",
      "womens"
    ]
  },
  {
    "title": "Recruitment of Lecturer in Govt. Polytechnic/Govt. Women's Polytechnic, Advt.No. 04/2026",
    "url": "/generated/posts/recruitment-of-lecturer-in-govt-polytechnic-govt-women-s-polytechnic-advt-no-04-2026.html",
    "category": "Recruitment",
    "department": "Teaching",
    "description": "",
    "keywords": [
      "042026",
      "2026",
      "advtno",
      "govt",
      "lecturer",
      "polytechnic",
      "polytechnicgovt",
      "recruitment",
      "teaching",
      "womens"
    ]
  },
  {
    "title": "Recruitment Advertisement for Scientific Officer Physics 2026 , Dated 16/03/2026",
    "url": "/generated/posts/recruitment-advertisement-for-scientific-officer-physics-2026-dated-16-03-2026.html",
    "category": "Recruitment",
    "department": "Government",
    "description": "",
    "keywords": [
      "16032026",
      "2026",
      "advertisement",
      "dated",
      "for",
      "government",
      "officer",
      "physics",
      "recruitment",
      "scientific"
    ]
  },
  {
    "title": "Recruitment Advertisement for Scientific Officer Chemistry 2026 , Dated 16/03/2026",
    "url": "/generated/posts/recruitment-advertisement-for-scientific-officer-chemistry-2026-dated-16-03-2026.html",
    "category": "Recruitment",
    "department": "Government",
    "description": "",
    "keywords": [
      "16032026",
      "2026",
      "advertisement",
      "chemistry",
      "dated",
      "for",
      "government",
      "officer",
      "recruitment",
      "scientific"
    ]
  },
  {
    "title": "Recruitment Advertisement for Scientific Officer Biology 2026 , Dated 16/03/2026",
    "url": "/generated/posts/recruitment-advertisement-for-scientific-officer-biology-2026-dated-16-03-2026.html",
    "category": "Recruitment",
    "department": "Government",
    "description": "",
    "keywords": [
      "16032026",
      "2026",
      "advertisement",
      "biology",
      "dated",
      "for",
      "government",
      "officer",
      "recruitment",
      "scientific"
    ]
  },
  {
    "title": "Recruitment Advertisement for Internal Accounts Examiner Officer Exam 2026 , Dated 10/04/2026",
    "url": "/generated/posts/recruitment-advertisement-for-internal-accounts-examiner-officer-exam-2026-dated-10-04-2026.html",
    "category": "Recruitment",
    "department": "Government",
    "description": "",
    "keywords": [
      "10042026",
      "2026",
      "accounts",
      "advertisement",
      "dated",
      "exam",
      "examiner",
      "for",
      "government",
      "internal",
      "officer",
      "recruitment"
    ]
  },
  {
    "title": "Recruitment Advertisement for Inspector of Boiler Grade 2, 2026 , Dated 21/01/2026",
    "url": "/generated/posts/recruitment-advertisement-for-inspector-of-boiler-grade-2-2026-dated-21-01-2026.html",
    "category": "Recruitment",
    "department": "Police",
    "description": "",
    "keywords": [
      "2026",
      "21012026",
      "advertisement",
      "boiler",
      "dated",
      "for",
      "government",
      "grade",
      "inspector",
      "recruitment"
    ]
  },
  {
    "title": "Recruitment Advertisement for Assistant Town Planner, 2026 , Dated 02/02/2026",
    "url": "/generated/posts/recruitment-advertisement-for-assistant-town-planner-2026-dated-02-02-2026.html",
    "category": "Recruitment",
    "department": "Government",
    "description": "",
    "keywords": [
      "02022026",
      "2026",
      "advertisement",
      "assistant",
      "dated",
      "for",
      "government",
      "planner",
      "recruitment",
      "town"
    ]
  },
  {
    "title": "Recruitment Advertisement for Assistant District Public Prosecution Officer 2026, Dated 10/03/2026",
    "url": "/generated/posts/recruitment-advertisement-for-assistant-district-public-prosecution-officer-2026-dated-10-03-2026.html",
    "category": "Recruitment",
    "department": "MPPSC",
    "description": "Official notification is available in PDF.",
    "keywords": [
      "10032026",
      "2026",
      "advertisement",
      "assistant",
      "dated",
      "district",
      "for",
      "mppsc",
      "officer",
      "prosecution",
      "public",
      "recruitment"
    ]
  },
  {
    "title": "Recruitment Advertisement for Assistant Director, Farmers Welfare and Agriculture Development 2026 , Dated 10/04/2026",
    "url": "/generated/posts/recruitment-advertisement-for-assistant-director-farmers-welfare-and-agriculture-development-2026-dated-10-04-2026.html",
    "category": "Recruitment",
    "department": "Agriculture",
    "description": "",
    "keywords": [
      "10042026",
      "2026",
      "advertisement",
      "agriculture",
      "and",
      "assistant",
      "dated",
      "development",
      "director",
      "farmers",
      "for",
      "government",
      "recruitment",
      "welfare"
    ]
  },
  {
    "title": "Recruitment Advertisement for Assistant Director Fisheries 2026, Department of Fishermen Welfare and Fisheries Development Government of Madhya Pradesh , Dated 06/07/2026",
    "url": "/generated/posts/recruitment-advertisement-for-assistant-director-fisheries-2026-department-of-fishermen-welfare-and-fisheries-development-government-of-madhya-pradesh-dated-06-07-2026.html",
    "category": "Recruitment",
    "department": "Government",
    "description": "",
    "keywords": [
      "06072026",
      "2026",
      "advertisement",
      "and",
      "assistant",
      "dated",
      "department",
      "development",
      "director",
      "fisheries",
      "fishermen",
      "for",
      "government",
      "madhya",
      "pradesh",
      "recruitment",
      "welfare"
    ]
  },
  {
    "title": "Recruitment Advertisement for Assistant Director 2026, Department of Higher Education, Government of Madhya Pradesh , Dated 06/07/2026",
    "url": "/generated/posts/recruitment-advertisement-for-assistant-director-2026-department-of-higher-education-government-of-madhya-pradesh-dated-06-07-2026.html",
    "category": "Recruitment",
    "department": "Government",
    "description": "",
    "keywords": [
      "06072026",
      "2026",
      "advertisement",
      "assistant",
      "dated",
      "department",
      "director",
      "education",
      "for",
      "government",
      "higher",
      "madhya",
      "pradesh",
      "recruitment"
    ]
  },
  {
    "title": "Recruitment Advertisement for Assistant Director /Veterinary Assistant Surgeon/Veterinary Extension Officer 2026 , Dated 10/03/2026",
    "url": "/generated/posts/recruitment-advertisement-for-assistant-director-veterinary-assistant-surgeon-veterinary-extension-officer-2026-dated-10-03-2026.html",
    "category": "Recruitment",
    "department": "Government",
    "description": "",
    "keywords": [
      "10032026",
      "2026",
      "advertisement",
      "assistant",
      "dated",
      "director",
      "extension",
      "for",
      "government",
      "officer",
      "recruitment",
      "surgeonveterinary",
      "veterinary"
    ]
  },
  {
    "title": "Recruitment Advertisement for Assistant Accounts Officer/Assistant Director Farmer Welfare and Agriculture Development Department 2026 , Dated 10/04/2026",
    "url": "/generated/posts/recruitment-advertisement-for-assistant-accounts-officer-assistant-director-farmer-welfare-and-agriculture-development-department-2026-dated-10-04-2026.html",
    "category": "Recruitment",
    "department": "Agriculture",
    "description": "",
    "keywords": [
      "10042026",
      "2026",
      "accounts",
      "advertisement",
      "agriculture",
      "and",
      "assistant",
      "dated",
      "department",
      "development",
      "director",
      "farmer",
      "for",
      "government",
      "officerassistant",
      "recruitment",
      "welfare"
    ]
  },
  {
    "title": "Online Application Link State Forest Service Main Exam 2026",
    "url": "/generated/posts/online-application-link-state-forest-service-main-exam-2026.html",
    "category": "Exam",
    "department": "Banking",
    "description": "",
    "keywords": [
      "2026",
      "application",
      "banking",
      "exam",
      "forest",
      "jobs",
      "latest",
      "link",
      "main",
      "online",
      "service",
      "state"
    ]
  },
  {
    "title": "Recruitment of Lecturer in Govt. Polytechnic/Govt. Women's Polytechnic(Regular), Advt.No.-04/2026",
    "url": "/generated/posts/recruitment-of-lecturer-in-govt-polytechnic-govt-women-s-polytechnic-regular-advt-no-04-2026.html",
    "category": "Recruitment",
    "department": "Teaching",
    "description": "Press Release regarding Combined Civil Services Main Examination Uploaded date:-09-07-2026",
    "keywords": [
      "2026",
      "advtno042026",
      "govt",
      "jpsc",
      "lecturer",
      "polytechnicgovt",
      "polytechnicregular",
      "recruitment",
      "womens"
    ]
  },
  {
    "title": "Recruitment of Lecturer in Govt. Polytechnic/Govt. Women's Polytechnic(Backlog),Advt.No.-03/2026",
    "url": "/generated/posts/recruitment-of-lecturer-in-govt-polytechnic-govt-women-s-polytechnic-backlog-advt-no-03-2026.html",
    "category": "Recruitment",
    "department": "Teaching",
    "description": "Press Release regarding Combined Civil Services Main Examination Uploaded date:-09-07-2026",
    "keywords": [
      "2026",
      "govt",
      "jpsc",
      "lecturer",
      "polytechnicbacklogadvtno032026",
      "polytechnicgovt",
      "recruitment",
      "womens"
    ]
  },
  {
    "title": "Recruitment of Jharkhand Combined Civil Services Examination-2025 Advt.No.-01/2026",
    "url": "/generated/posts/recruitment-of-jharkhand-combined-civil-services-examination-2025-advt-no-01-2026-4106554356.html",
    "category": "Recruitment",
    "department": "JPSC",
    "description": "",
    "keywords": [
      "2025",
      "advtno012026",
      "civil",
      "combined",
      "examination2025",
      "jharkhand",
      "jpsc",
      "recruitment",
      "services"
    ]
  },
  {
    "title": "Recruitment of Jharkhand Combined Civil Services Examination (Backlog)-2025 Advt.No.-05/2026",
    "url": "/generated/posts/recruitment-of-jharkhand-combined-civil-services-examination-backlog-2025-advt-no-05-2026.html",
    "category": "Recruitment",
    "department": "JPSC",
    "description": "Press Release regarding Combined Civil Services Main Examination Uploaded date:-09-07-2026",
    "keywords": [
      "2025",
      "advtno052026",
      "backlog2025",
      "civil",
      "combined",
      "examination",
      "jharkhand",
      "jpsc",
      "recruitment",
      "services"
    ]
  },
  {
    "title": "Recruitment of Jharkhand Combined Civil Services Examination (Backlog)-2023 Advt.No.-06/2026",
    "url": "/generated/posts/recruitment-of-jharkhand-combined-civil-services-examination-backlog-2023-advt-no-06-2026.html",
    "category": "Recruitment",
    "department": "JPSC",
    "description": "Press Release regarding Combined Civil Services Main Examination Uploaded date:-09-07-2026",
    "keywords": [
      "2023",
      "advtno062026",
      "backlog2023",
      "civil",
      "combined",
      "examination",
      "jharkhand",
      "jpsc",
      "recruitment",
      "services"
    ]
  },
  {
    "title": "Recruitment of Assistant Professor in Medical Colleges(Super Specialist)Department Advt.No.-07/2026",
    "url": "/generated/posts/recruitment-of-assistant-professor-in-medical-colleges-super-specialist-department-advt-no-07-2026.html",
    "category": "Recruitment",
    "department": "Teaching",
    "description": "Press Release regarding Combined Civil Services Main Examination Uploaded date:-09-07-2026",
    "keywords": [
      "2026",
      "advtno072026",
      "assistant",
      "collegessuper",
      "jpsc",
      "medical",
      "professor",
      "recruitment",
      "specialistdepartment"
    ]
  },
  {
    "title": "Recruitment of Assistant Professor in Government Engineering colleges (Backlog),Advt.No.-02/2026",
    "url": "/generated/posts/recruitment-of-assistant-professor-in-government-engineering-colleges-backlog-advt-no-02-2026.html",
    "category": "Recruitment",
    "department": "Teaching",
    "description": "",
    "keywords": [
      "2026",
      "assistant",
      "backlogadvtno022026",
      "colleges",
      "engineering",
      "government",
      "jpsc",
      "professor",
      "recruitment"
    ]
  },
  {
    "title": "Recruitment Advertisement for Scientific Officer Physics 2026 (Adv No./05/2026), Dated 16/03/2026",
    "url": "/generated/posts/recruitment-advertisement-for-scientific-officer-physics-2026-adv-no-05-2026-dated-16-03-2026.html",
    "category": "Recruitment",
    "department": "MPPSC",
    "description": "Official notification is available in PDF.",
    "keywords": [
      "16032026",
      "2026",
      "adv",
      "advertisement",
      "dated",
      "for",
      "mppsc",
      "no052026",
      "officer",
      "physics",
      "recruitment",
      "scientific"
    ]
  },
  {
    "title": "Recruitment Advertisement for Scientific Officer Chemistry 2026 (Adv No./06/2026), Dated 16/03/2026",
    "url": "/generated/posts/recruitment-advertisement-for-scientific-officer-chemistry-2026-adv-no-06-2026-dated-16-03-2026.html",
    "category": "Recruitment",
    "department": "MPPSC",
    "description": "Official notification is available in PDF.",
    "keywords": [
      "16032026",
      "2026",
      "adv",
      "advertisement",
      "chemistry",
      "dated",
      "for",
      "mppsc",
      "no062026",
      "officer",
      "recruitment",
      "scientific"
    ]
  },
  {
    "title": "Recruitment Advertisement for Scientific Officer Biology 2026 (Adv No./07/2026), Dated 16/03/2026",
    "url": "/generated/posts/recruitment-advertisement-for-scientific-officer-biology-2026-adv-no-07-2026-dated-16-03-2026.html",
    "category": "Recruitment",
    "department": "MPPSC",
    "description": "Official notification is available in PDF.",
    "keywords": [
      "16032026",
      "2026",
      "adv",
      "advertisement",
      "biology",
      "dated",
      "for",
      "mppsc",
      "no072026",
      "officer",
      "recruitment",
      "scientific"
    ]
  },
  {
    "title": "Recruitment Advertisement for Internal Accounts Examiner Officer Exam 2026 (Advt. No./10/2026), Dated 10/04/2026",
    "url": "/generated/posts/recruitment-advertisement-for-internal-accounts-examiner-officer-exam-2026-advt-no-10-2026-dated-10-04-2026.html",
    "category": "Recruitment",
    "department": "MPPSC",
    "description": "Official notification is available in PDF.",
    "keywords": [
      "10042026",
      "2026",
      "accounts",
      "advertisement",
      "advt",
      "dated",
      "exam",
      "examiner",
      "for",
      "internal",
      "mppsc",
      "no102026",
      "officer",
      "recruitment"
    ]
  },
  {
    "title": "Recruitment Advertisement for Inspector of Boiler Grade-2, 2026 (Industrial Policy and Investment Promotion Department - Government of Madhya Pradesh) (Advt. No./01/2026), Dated 21/01/2026",
    "url": "/generated/posts/recruitment-advertisement-for-inspector-of-boiler-grade-2-2026-industrial-policy-and-investment-promotion-department-government-of-madhya-pradesh-advt-no-01-2026-dated-21-01-2026.html",
    "category": "Recruitment",
    "department": "Police",
    "description": "Official notification is available in PDF.",
    "keywords": [
      "2026",
      "21012026",
      "advertisement",
      "advt",
      "and",
      "boiler",
      "dated",
      "department",
      "for",
      "government",
      "grade2",
      "industrial",
      "inspector",
      "investment",
      "madhya",
      "mppsc",
      "no012026",
      "policy",
      "pradesh",
      "promotion",
      "recruitment"
    ]
  },
  {
    "title": "Recruitment Advertisement for Assistant Town Planner, 2026 (Urban Development Department - Government of Madhya Pradesh) (Advt. No./02/2026), Dated 02/02/2026",
    "url": "/generated/posts/recruitment-advertisement-for-assistant-town-planner-2026-urban-development-department-government-of-madhya-pradesh-advt-no-02-2026-dated-02-02-2026.html",
    "category": "Recruitment",
    "department": "MPPSC",
    "description": "Official notification is available in PDF.",
    "keywords": [
      "02022026",
      "2026",
      "advertisement",
      "advt",
      "assistant",
      "dated",
      "department",
      "development",
      "for",
      "government",
      "madhya",
      "mppsc",
      "no022026",
      "planner",
      "pradesh",
      "recruitment",
      "town",
      "urban"
    ]
  },
  {
    "title": "Recruitment Advertisement for Assistant Director, Farmers Welfare and Agriculture Development (Statistics) 2026 (Advt. No./09/2026), Dated 10/04/2026",
    "url": "/generated/posts/recruitment-advertisement-for-assistant-director-farmers-welfare-and-agriculture-development-statistics-2026-advt-no-09-2026-dated-10-04-2026.html",
    "category": "Recruitment",
    "department": "Agriculture",
    "description": "Official notification is available in PDF.",
    "keywords": [
      "10042026",
      "2026",
      "advertisement",
      "advt",
      "agriculture",
      "and",
      "assistant",
      "dated",
      "development",
      "director",
      "farmers",
      "for",
      "mppsc",
      "no092026",
      "recruitment",
      "statistics",
      "welfare"
    ]
  },
  {
    "title": "Recruitment Advertisement for Assistant Director Fisheries 2026, Department of Fishermen Welfare and Fisheries Development Government of Madhya Pradesh (Advt. No. 11/2026), Dated 06/07/2026",
    "url": "/generated/posts/recruitment-advertisement-for-assistant-director-fisheries-2026-department-of-fishermen-welfare-and-fisheries-development-government-of-madhya-pradesh-advt-no-11-2026-dated-06-07-2026.html",
    "category": "Recruitment",
    "department": "MPPSC",
    "description": "Official notification is available in PDF.",
    "keywords": [
      "06072026",
      "112026",
      "2026",
      "advertisement",
      "advt",
      "and",
      "assistant",
      "dated",
      "department",
      "development",
      "director",
      "fisheries",
      "fishermen",
      "for",
      "government",
      "madhya",
      "mppsc",
      "pradesh",
      "recruitment",
      "welfare"
    ]
  },
  {
    "title": "Recruitment Advertisement for Assistant Director 2026, Department of Higher Education, Government of Madhya Pradesh (Advt. No. 12/2026), Dated 06/07/2026",
    "url": "/generated/posts/recruitment-advertisement-for-assistant-director-2026-department-of-higher-education-government-of-madhya-pradesh-advt-no-12-2026-dated-06-07-2026.html",
    "category": "Recruitment",
    "department": "MPPSC",
    "description": "Official notification is available in PDF.",
    "keywords": [
      "06072026",
      "122026",
      "2026",
      "advertisement",
      "advt",
      "assistant",
      "dated",
      "department",
      "director",
      "education",
      "for",
      "government",
      "higher",
      "madhya",
      "mppsc",
      "pradesh",
      "recruitment"
    ]
  },
  {
    "title": "Recruitment Advertisement for Assistant Director /Veterinary Assistant Surgeon/Veterinary Extension Officer 2026 (Adv No./04/2026), Dated 10/03/2026",
    "url": "/generated/posts/recruitment-advertisement-for-assistant-director-veterinary-assistant-surgeon-veterinary-extension-officer-2026-adv-no-04-2026-dated-10-03-2026.html",
    "category": "Recruitment",
    "department": "MPPSC",
    "description": "Official notification is available in PDF.",
    "keywords": [
      "10032026",
      "2026",
      "adv",
      "advertisement",
      "assistant",
      "dated",
      "director",
      "extension",
      "for",
      "mppsc",
      "no042026",
      "officer",
      "recruitment",
      "surgeonveterinary",
      "veterinary"
    ]
  },
  {
    "title": "Recruitment Advertisement for Assistant Accounts Officer/Assistant Director Farmer Welfare and Agriculture Development Department (Accounts and Establishment) 2026 (Advt. No. 08/2026), Dated 10/04/2026",
    "url": "/generated/posts/recruitment-advertisement-for-assistant-accounts-officer-assistant-director-farmer-welfare-and-agriculture-development-department-accounts-and-establishment-2026-advt-no-08-2026-dated-10-04-2026.html",
    "category": "Recruitment",
    "department": "Agriculture",
    "description": "Official notification is available in PDF.",
    "keywords": [
      "082026",
      "10042026",
      "2026",
      "accounts",
      "advertisement",
      "advt",
      "agriculture",
      "and",
      "assistant",
      "dated",
      "department",
      "development",
      "director",
      "establishment",
      "farmer",
      "for",
      "mppsc",
      "officerassistant",
      "recruitment",
      "welfare"
    ]
  },
  {
    "title": "Online Preliminary Exam Call Letter for CRP PO/MT-XVI - Probationary Officers / Management Trainees",
    "url": "/generated/posts/online-preliminary-exam-call-letter-for-crp-po-mt-xvi-probationary-officers-management-trainees-0195582790.html",
    "category": "Admit Card",
    "department": "IBPS",
    "description": "Home / CRP PO/MT s / PO/MTs XVI Probationary Officers / Management Trainees XVI Date Details 14 Aug 2026 Online Preliminary Exam Call Letter for CRP PO/MT-XVI - Probationary Officers / Management Trainees 14 Aug 2026 Information Handout for Online Preliminary Exam for CRP PO/MT-XVI-Probationary Officers / Management Trainees (English) 14 Aug 2026 Information Handout for Online Preliminary Exam for CRP PO/MT-XVI-Probationary Officers / Management Trainees (Hindi) 14 Aug 2026 Link for Online Scrib",
    "keywords": [
      "admit",
      "call",
      "card",
      "crp",
      "exam",
      "for",
      "ibps",
      "letter",
      "management",
      "officers",
      "online",
      "pomtxvi",
      "preliminary",
      "probationary",
      "trainees"
    ]
  },
  {
    "title": "Online Application Link - State Forest Service Main Exam 2026",
    "url": "/generated/posts/online-application-link-state-forest-service-main-exam-2026-44c0c44d94.html",
    "category": "Exam",
    "department": "MPPSC",
    "description": "",
    "keywords": [
      "2026",
      "application",
      "exam",
      "forest",
      "link",
      "main",
      "mppsc",
      "online",
      "service",
      "state"
    ]
  },
  {
    "title": "Notice regarding recruitment of Jharkhand Combined Civil Services Examination-2025 Advt.No.-01/2026 (29-07-2026)",
    "url": "/generated/posts/notice-regarding-recruitment-of-jharkhand-combined-civil-services-examination-2025-advt-no-01-2026-29-07-2026.html",
    "category": "Recruitment",
    "department": "JPSC",
    "description": "Official notification is available in PDF.",
    "keywords": [
      "2025",
      "29072026",
      "advtno012026",
      "civil",
      "combined",
      "examination2025",
      "jharkhand",
      "jpsc",
      "notice",
      "recruitment",
      "regarding",
      "services"
    ]
  },
  {
    "title": "FILL ONLINE DETAILS FOR ADVT. NO.A-6/E-1/2026, LECTURER (MALE/FEMALE) GOVERNMENT INTER COLLEGE (MAINS) EXAM.-2025.",
    "url": "/generated/posts/fill-online-details-for-advt-no-a-6-e-1-2026-lecturer-male-female-government-inter-college-mains-exam-2025.html",
    "category": "Recruitment",
    "department": "Teaching",
    "description": "",
    "keywords": [
      "2026",
      "advt",
      "college",
      "details",
      "exam2025",
      "fill",
      "for",
      "government",
      "inter",
      "lecturer",
      "mains",
      "malefemale",
      "noa6e12026",
      "online",
      "recruitment",
      "uppsc"
    ]
  },
  {
    "title": "FILL ONLINE DETAILS FOR ADVT. NO.A-6/E-1/2026, LECTURER (MALE/FEMALE) GOVERNMENT INTER COLLEGE (MAINS) EXAM.-2025(U.P. JAIL TRAINING SCHOOL SERVICE).",
    "url": "/generated/posts/fill-online-details-for-advt-no-a-6-e-1-2026-lecturer-male-female-government-inter-college-mains-exam-2025-u-p-jail-training-school-service.html",
    "category": "Recruitment",
    "department": "Teaching",
    "description": "",
    "keywords": [
      "2026",
      "advt",
      "college",
      "details",
      "exam2025up",
      "fill",
      "for",
      "government",
      "inter",
      "jail",
      "lecturer",
      "mains",
      "malefemale",
      "noa6e12026",
      "online",
      "recruitment",
      "school",
      "service",
      "training",
      "uppsc"
    ]
  },
  {
    "title": "Corrigendum: Integrated 72nd Combined (Preliminary) Competitive Examination – Deletion of 44 Vacancies of Sugarcane Officer.",
    "url": "/generated/posts/corrigendum-integrated-72nd-combined-preliminary-competitive-examination-deletion-of-44-vacancies-of-sugarcane-officer.html",
    "category": "Recruitment",
    "department": "BPSC",
    "description": "Official notification is available in PDF.",
    "keywords": [
      "72nd",
      "bpsc",
      "combined",
      "competitive",
      "corrigendum",
      "deletion",
      "examination",
      "integrated",
      "officer",
      "preliminary",
      "recruitment",
      "sugarcane",
      "vacancies"
    ]
  },
  {
    "title": "24 Oct 2026 CORRIGENDUM NOTICE REGARDING ADVT.NO.D-6/E-1/2025, DIRECTORATE OF HOMOEOPATHY UTTAR PRADESH / HOMOEOPATHIC MEDICAL OFFICER, S-11/32",
    "url": "/generated/posts/24-oct-2026-corrigendum-notice-regarding-advt-no-d-6-e-1-2025-directorate-of-homoeopathy-uttar-pradesh-homoeopathic-medical-officer-s-1-c9829de70e.html",
    "category": "Recruitment",
    "department": "Medical",
    "description": "",
    "keywords": [
      "2026",
      "advtnod6e12025",
      "corrigendum",
      "directorate",
      "homoeopathic",
      "homoeopathy",
      "medical",
      "notice",
      "oct",
      "officer",
      "pradesh",
      "recruitment",
      "regarding",
      "s1132",
      "uppsc",
      "uttar"
    ]
  },
  {
    "title": "27 Aug 2026 NOTICE REGARDING ADVT. NO. A-3/E-1/2016, REVIEW OFFICER/ASSTT. REVIEW OFFICER ETC. (GENERAL/SPECIAL RECTT.) EXAMINATION-2016",
    "url": "/generated/posts/27-aug-2026-notice-regarding-advt-no-a-3-e-1-2016-review-officer-asstt-review-officer-etc-general-special-rectt-examination-2016.html",
    "category": "Recruitment",
    "department": "UPPSC",
    "description": "",
    "keywords": [
      "2026",
      "a3e12016",
      "advt",
      "aug",
      "etc",
      "examination2016",
      "generalspecial",
      "notice",
      "officer",
      "officerasstt",
      "recruitment",
      "rectt",
      "regarding",
      "review",
      "uppsc"
    ]
  },
  {
    "title": "19 Aug 2026 NOTICE REGARDING ADVT. NO. A-6/E-1/2025, LECTURER (MALE/FEMALE) GOVERNMENT INTER COLLEGE (MAINS) EXAM.-2025",
    "url": "/generated/posts/19-aug-2026-notice-regarding-advt-no-a-6-e-1-2025-lecturer-male-female-government-inter-college-mains-exam-2025.html",
    "category": "Recruitment",
    "department": "Teaching",
    "description": "",
    "keywords": [
      "2026",
      "a6e12025",
      "advt",
      "aug",
      "college",
      "exam2025",
      "government",
      "inter",
      "lecturer",
      "mains",
      "malefemale",
      "notice",
      "recruitment",
      "regarding",
      "teaching"
    ]
  },
  {
    "title": "FILL ONLINE DETAILS FOR ADVT. NO.A-7/E-1/2026, ASSISTANT PROFESSOR, GOVERNMENT DEGREE COLLEGE (MAINS) EXAM.-2025.",
    "url": "/generated/posts/fill-online-details-for-advt-no-a-7-e-1-2026-assistant-professor-government-degree-college-mains-exam-2025.html",
    "category": "Recruitment",
    "department": "Teaching",
    "description": "",
    "keywords": [
      "2026",
      "advt",
      "assistant",
      "college",
      "degree",
      "details",
      "exam2025",
      "fill",
      "for",
      "government",
      "mains",
      "noa7e12026",
      "online",
      "professor",
      "recruitment",
      "teaching"
    ]
  }
];