window.searchData = [
  {
    "title": "Syllabus for the posts of Senior Court Assistant-cum-Senior Programmer and Junior Court Assistant-cum-Junior Programmer",
    "url": "/generated/posts/syllabus-for-the-posts-of-senior-court-assistant-cum-senior-programmer-and-junior-court-assistant-cum-junior-programmer-d3be14119e.html",
    "category": "Syllabus",
    "department": "Government",
    "state": "",
    "description": "",
    "keywords": [
      "and",
      "assistantcumjunior",
      "assistantcumsenior",
      "court",
      "for",
      "government",
      "junior",
      "posts",
      "programmer",
      "senior",
      "syllabus",
      "the"
    ]
  },
  {
    "title": "Syllabus and outlines for Computer Knowledge Test for the ex-cadre post of Additional Registrar (Housekeeping)",
    "url": "/generated/posts/syllabus-and-outlines-for-computer-knowledge-test-for-the-ex-cadre-post-of-additional-registrar-housekeeping-6fb1858cef.html",
    "category": "Syllabus",
    "department": "Government",
    "state": "",
    "description": "",
    "keywords": [
      "additional",
      "and",
      "computer",
      "excadre",
      "for",
      "government",
      "housekeeping",
      "knowledge",
      "outlines",
      "post",
      "registrar",
      "syllabus",
      "test",
      "the"
    ]
  },
  {
    "title": "Scholarship / Fellowships",
    "url": "/generated/posts/scholarship-fellowships-2f367429e6.html",
    "category": "Scholarship",
    "department": "Government",
    "state": "",
    "description": "",
    "keywords": [
      "fellowships",
      "government",
      "scholarship"
    ]
  },
  {
    "title": "Revised Result: Final selection of Neha Singh for the post of Fireman Driver in Bihar Fire Services.",
    "url": "/generated/posts/revised-result-final-selection-of-neha-singh-for-the-post-of-fireman-driver-in-bihar-fire-services-9e2b3399d7.html",
    "category": "Recruitment",
    "department": "Government",
    "state": "",
    "description": "",
    "keywords": [
      "bihar",
      "driver",
      "final",
      "fire",
      "fireman",
      "for",
      "government",
      "neha",
      "post",
      "recruitment",
      "result",
      "revised",
      "selection",
      "services",
      "singh",
      "the"
    ]
  },
  {
    "title": "Results: Finally selected candidates for the post of Driver Constable in Bihar Police organization.",
    "url": "/generated/posts/results-finally-selected-candidates-for-the-post-of-driver-constable-in-bihar-police-organization-67e60386ec.html",
    "category": "Result",
    "department": "Police",
    "state": "",
    "description": "",
    "keywords": [
      "bihar",
      "candidates",
      "constable",
      "driver",
      "finally",
      "for",
      "organization",
      "police",
      "post",
      "result",
      "results",
      "selected",
      "the"
    ]
  },
  {
    "title": "Results: Finally selected candidates for the post of Driver Constable & Fireman Driver in Bihar Police/Bihar Fire Services.",
    "url": "/generated/posts/results-finally-selected-candidates-for-the-post-of-driver-constable-and-fireman-driver-in-bihar-police-bihar-fire-services-26e195d369.html",
    "category": "Result",
    "department": "Police",
    "state": "",
    "description": "",
    "keywords": [
      "bihar",
      "candidates",
      "constable",
      "driver",
      "finally",
      "fire",
      "fireman",
      "for",
      "police",
      "policebihar",
      "post",
      "result",
      "results",
      "selected",
      "services",
      "the"
    ]
  },
  {
    "title": "Results: Finally selected candidates for the post of Constable in Bihar Police.",
    "url": "/generated/posts/results-finally-selected-candidates-for-the-post-of-constable-in-bihar-police-06708935c2.html",
    "category": "Result",
    "department": "Police",
    "state": "",
    "description": "",
    "keywords": [
      "bihar",
      "candidates",
      "constable",
      "finally",
      "for",
      "police",
      "post",
      "result",
      "results",
      "selected",
      "the"
    ]
  },
  {
    "title": "Results: Finally selected candidates for the post of Constable in Bihar Police, Bihar Military Police, Special India Reserve Battalion and Bihar State Industrial Security Battalion.",
    "url": "/generated/posts/results-finally-selected-candidates-for-the-post-of-constable-in-bihar-police-bihar-military-police-special-india-reserve-battalio-b31ac25116.html",
    "category": "Result",
    "department": "Police",
    "state": "",
    "description": "",
    "keywords": [
      "and",
      "battalion",
      "bihar",
      "candidates",
      "constable",
      "finally",
      "for",
      "india",
      "industrial",
      "military",
      "police",
      "post",
      "reserve",
      "result",
      "results",
      "security",
      "selected",
      "special",
      "state",
      "the"
    ]
  },
  {
    "title": "Results: Final Selection List of Candidates for the Post of Constable in Bihar Police.",
    "url": "/generated/posts/results-final-selection-list-of-candidates-for-the-post-of-constable-in-bihar-police-8c62773385.html",
    "category": "Result",
    "department": "Police",
    "state": "",
    "description": "",
    "keywords": [
      "bihar",
      "candidates",
      "constable",
      "final",
      "for",
      "list",
      "police",
      "post",
      "result",
      "results",
      "selection",
      "the"
    ]
  },
  {
    "title": "Results: Final Result of Bihar Swabhiman Police Battalion Constable .",
    "url": "/generated/posts/results-final-result-of-bihar-swabhiman-police-battalion-constable-1a43c4a44e.html",
    "category": "Result",
    "department": "Police",
    "state": "",
    "description": "",
    "keywords": [
      "battalion",
      "bihar",
      "constable",
      "final",
      "police",
      "result",
      "results",
      "swabhiman"
    ]
  },
  {
    "title": "Results: Final result for the post of Constable in Bihar Police.",
    "url": "/generated/posts/results-final-result-for-the-post-of-constable-in-bihar-police-711b91d44d.html",
    "category": "Recruitment",
    "department": "Police",
    "state": "",
    "description": "",
    "keywords": [
      "bihar",
      "constable",
      "final",
      "for",
      "police",
      "post",
      "recruitment",
      "result",
      "results",
      "the"
    ]
  },
  {
    "title": "Result of candidates who qualified Objective Type Written Test (including Computer Knowledge Test) and Shorthand Skill Test for the post of Senior Personal Assistant",
    "url": "/generated/posts/result-of-candidates-who-qualified-objective-type-written-test-including-computer-knowledge-test-and-shorthand-skill-test-for-the-83c6213d5b.html",
    "category": "Result",
    "department": "Government",
    "state": "",
    "description": "",
    "keywords": [
      "and",
      "assistant",
      "candidates",
      "computer",
      "for",
      "government",
      "including",
      "knowledge",
      "objective",
      "personal",
      "post",
      "qualified",
      "result",
      "senior",
      "shorthand",
      "skill",
      "test",
      "the",
      "type",
      "who",
      "written"
    ]
  },
  {
    "title": "RECRUITMENTOF SPECIALIST CADRE OFFICERS ON CONTRACTUAL BASIS (FINAL RESULT ANNOUNCED)",
    "url": "/generated/posts/recruitmentof-specialist-cadre-officers-on-contractual-basis-final-result-announced-5cdb4a7b0e.html",
    "category": "Banking Jobs",
    "department": "Banking",
    "state": "",
    "description": "RECRUITMENTOF SPECIALIST CADRE OFFICERS ON CONTRACTUAL BASIS (FINAL RESULT ANNOUNCED) ADVERTISEMENT NO: CRPD/SCO/2024-25/19 DOWNLOAD ADVERTISEMENT( Hindi / English ) FINAL RESULT (NEW)",
    "keywords": [
      "announced",
      "banking",
      "basis",
      "cadre",
      "contractual",
      "final",
      "officers",
      "recruitment",
      "recruitmentof",
      "result",
      "specialist"
    ]
  },
  {
    "title": "RECRUITMENT OF SPECIALIST CADRE OFFICERS ON REGULAR BASIS DEPUTY MANAGER (SYSTEMS) & ASSISTANT MANAGER (SYSTEM) (FINAL RESULT ANNOUNCED)",
    "url": "/generated/posts/recruitment-of-specialist-cadre-officers-on-regular-basis-deputy-manager-systems-and-assistant-manager-system-final-result-announc-83222e4481.html",
    "category": "Banking Jobs",
    "department": "Banking",
    "state": "",
    "description": "RECRUITMENT OF SPECIALIST CADRE OFFICERS ON REGULAR BASIS DEPUTY MANAGER (SYSTEMS) & ASSISTANT MANAGER (SYSTEM) (FINAL RESULT ANNOUNCED) ADVERTISEMENT NO : CRPD/SCO/2024-25/15 DOWNLOAD ADVERTISEMENT( Hindi / English ) ADDENDUM FINAL RESULT – ASSISTANT MANAGER (SYSTEM) (NEW) FINAL RESULT - DEPUTY MANAGER (SYSTEMS) - PROJECT MANAGEMENT & DELIVERY (NEW) FINAL RESULT - DEPUTY MANAGER (SYSTEMS) - INFRA SUPPORT & CLOUD OPERATIONS (NEW) FINAL RESULT - DEPUTY MANAGER (SYSTEMS) - NETWORKING OPERATIONS (NEW) FINAL RESULT - DEPUTY MANAGER (SYSTEMS) - IT ARCHITECT (NEW) FINAL RESULT - DEPUTY MANAGER (SYSTEMS) - INFORMATION SECURITY (NEW) RECRUITMENT OF SPECIALIST CADRE OFFICER ON CONTRACTUAL BASIS (Fina",
    "keywords": [
      "announced",
      "assistant",
      "banking",
      "basis",
      "cadre",
      "deputy",
      "final",
      "manager",
      "officers",
      "recruitment",
      "regular",
      "result",
      "specialist",
      "system",
      "systems"
    ]
  },
  {
    "title": "RECRUITMENT OF SPECIALIST CADRE OFFICERS ON REGULAR BASIS (Final Result Announced )",
    "url": "/generated/posts/recruitment-of-specialist-cadre-officers-on-regular-basis-final-result-announced-a57050fb88.html",
    "category": "Banking Jobs",
    "department": "Banking",
    "state": "",
    "description": "RECRUITMENT OF SPECIALIST CADRE OFFICERS ON REGULAR BASIS (Final Result Announced ) ADVERTISEMENT NO : CRPD/SCO/2024-25/11 DOWNLOAD ADVERTISEMENT( Hindi / English ) FINAL RESULT (NEW) RECRUITMENT OF SPECIALIST CADRE OFFICER ON REGULAR & CONTRACTUAL BASIS (Final Result Announced ) ADVERTISEMENT NO : CRPD/SCO/2024-25/10 DOWNLOAD ADVERTISEMENT( Hindi / English ) FINAL RESULT (NEW) ENGAGEMENT OF RETIRED BANK OFFICERS ON CONTRACT BASIS (Final Result Announced) ADVERTISEMENT NO : CRPD/RS/2024-25/08 DOWNLOAD ADVERTISEMENT( Hindi / English ) FINAL RESULT (NEW) RECRUITMENT OF SPECIALIST CADRE OFFICERS ON CONTRACTUAL BASIS (Final Result Announced ) ADVERTISEMENT NO : CRPD/SCO/2024-25/06 DOWNLOAD ADVER",
    "keywords": [
      "announced",
      "banking",
      "basis",
      "cadre",
      "final",
      "officers",
      "recruitment",
      "regular",
      "result",
      "specialist"
    ]
  },
  {
    "title": "RECRUITMENT OF SPECIALIST CADRE OFFICERS ON CONTRACTUAL BASIS (Final Result Announced )",
    "url": "/generated/posts/recruitment-of-specialist-cadre-officers-on-contractual-basis-final-result-announced-136d99d647.html",
    "category": "Banking Jobs",
    "department": "Banking",
    "state": "",
    "description": "RECRUITMENT OF SPECIALIST CADRE OFFICERS ON CONTRACTUAL BASIS (Final Result Announced ) ADVERTISEMENT NO : CRPD/SCO/2024-25/06 DOWNLOAD ADVERTISEMENT( Hindi / English ) FINAL RESULT (NEW) RECRUITMENT OF SPECIALIST CADRE OFFICERS ON REGULAR BASIS (Final Result Announced ) ADVERTISEMENT NO : CRPD/SCO/2024-25/05 DOWNLOAD ADVERTISEMENT( Hindi / English ) FINAL RESULT (NEW) RECRUITMENT OF SPECIALIST CADRE OFFICERS ON REGULAR BASIS (FINAL RESULT ANNOUNCED ) ADVERTISEMENT NO : CRPD/SCO/2024-25/04 DOWNLOAD ADVERTISEMENT( Hindi / English ) FINAL RESULT (NEW) RECRUITMENT OF SPECIALIST CADRE OFFICERS ON CONTRACTUAL BASIS (Final Result Announced ) ADVERTISEMENT NO : CRPD/SCO/2024-25/03 DOWNLOAD ADVERTIS",
    "keywords": [
      "announced",
      "banking",
      "basis",
      "cadre",
      "contractual",
      "final",
      "officers",
      "recruitment",
      "result",
      "specialist"
    ]
  },
  {
    "title": "RECRUITMENT OF SPECIALIST CADRE OFFICER ON REGULAR BASIS FOR THE POST OF BANK MEDICAL OFFICER (CALL LETTER FOR ONLINE WRITTEN EXAMINATION SCHEDULED ON 23.08.2026 IS AVAILABLE FOR DOWNLOAD)",
    "url": "/generated/posts/recruitment-of-specialist-cadre-officer-on-regular-basis-for-the-post-of-bank-medical-officer-call-letter-for-online-written-exami-a115601a4c.html",
    "category": "Banking Jobs",
    "department": "Banking",
    "state": "",
    "description": "RECRUITMENT OF SPECIALIST CADRE OFFICER ON REGULAR BASIS FOR THE POST OF BANK MEDICAL OFFICER (CALL LETTER FOR ONLINE WRITTEN EXAMINATION SCHEDULED ON 23.08.2026 IS AVAILABLE FOR DOWNLOAD) ADVERTISEMENT NO:CRPD/SCO/2026-27/03 DOWNLOAD ADVERTISEMENT (Hindi (577 KB) / English (1022 KB) ) (NEW) DOWNLOAD ONLINE WRITTEN EXAMINATION CALL LETTER (NEW) DOWNLOAD ACQUAINT YOURSELF BOOKLET( Hindi (704 KB) / English (476 KB) ) (NEW)",
    "keywords": [
      "2026",
      "23082026",
      "admit",
      "available",
      "bank",
      "banking",
      "basis",
      "cadre",
      "call",
      "card",
      "download",
      "examination",
      "for",
      "letter",
      "medical",
      "officer",
      "online",
      "post",
      "recruitment",
      "regular",
      "scheduled",
      "specialist",
      "the",
      "written"
    ]
  },
  {
    "title": "RECRUITMENT OF SPECIALIST CADRE OFFICER ON REGULAR BASIS FOR THE POST OF ASSISTANT MANAGER (LAW) & DEPUTY MANAGER (LAW) (CALL LETTER FOR ONLINE WRITTEN EXAMINATION SCHEDULED ON 23.08.2026 IS AVAILABLE FOR DOWNLOAD)",
    "url": "/generated/posts/recruitment-of-specialist-cadre-officer-on-regular-basis-for-the-post-of-assistant-manager-law-and-deputy-manager-law-call-letter-d499eaf37d.html",
    "category": "Banking Jobs",
    "department": "Banking",
    "state": "",
    "description": "RECRUITMENT OF SPECIALIST CADRE OFFICER ON REGULAR BASIS FOR THE POST OF ASSISTANT MANAGER (LAW) & DEPUTY MANAGER (LAW) (CALL LETTER FOR ONLINE WRITTEN EXAMINATION SCHEDULED ON 23.08.2026 IS AVAILABLE FOR DOWNLOAD) ADVERTISEMENT NO:CRPD/SCO/2026-27/02 DOWNLOAD ADVERTISEMENT (Hindi (542 KB) / English (980 KB) ) (NEW) DOWNLOAD ONLINE WRITTEN EXAMINATION CALL LETTER (NEW) DOWNLOAD ACQUAINT YOURSELF BOOKLET (Hindi (626 KB) / English (380) )(NEW) SCRIBE GUIDELINES (408 KB) (NEW)",
    "keywords": [
      "2026",
      "23082026",
      "admit",
      "assistant",
      "available",
      "banking",
      "basis",
      "cadre",
      "call",
      "card",
      "deputy",
      "download",
      "examination",
      "for",
      "law",
      "letter",
      "manager",
      "officer",
      "online",
      "post",
      "recruitment",
      "regular",
      "scheduled",
      "specialist",
      "the",
      "written"
    ]
  },
  {
    "title": "RECRUITMENT OF SPECIALIST CADRE OFFICER ON REGULAR BASIS (FINAL RESULT ANNOUNCED)",
    "url": "/generated/posts/recruitment-of-specialist-cadre-officer-on-regular-basis-final-result-announced-5916c69256.html",
    "category": "Banking Jobs",
    "department": "Banking",
    "state": "",
    "description": "RECRUITMENT OF SPECIALIST CADRE OFFICER ON REGULAR BASIS (FINAL RESULT ANNOUNCED) ADVERTISEMENT NO: CRPD/SCO/2025-26/14 DOWNLOAD ADVERTISEMENT( Hindi / English ) FINAL RESULT (NEW)",
    "keywords": [
      "announced",
      "banking",
      "basis",
      "cadre",
      "final",
      "officer",
      "recruitment",
      "regular",
      "result",
      "specialist"
    ]
  },
  {
    "title": "RECRUITMENT OF SPECIALIST CADRE OFFICER ON REGULAR & CONTRACTUAL BASIS (Final Result Announced )",
    "url": "/generated/posts/recruitment-of-specialist-cadre-officer-on-regular-and-contractual-basis-final-result-announced-ba7ddb6839.html",
    "category": "Banking Jobs",
    "department": "Banking",
    "state": "",
    "description": "RECRUITMENT OF SPECIALIST CADRE OFFICER ON REGULAR & CONTRACTUAL BASIS (Final Result Announced ) ADVERTISEMENT NO : CRPD/SCO/2024-25/10 DOWNLOAD ADVERTISEMENT( Hindi / English ) FINAL RESULT (NEW) ENGAGEMENT OF RETIRED BANK OFFICERS ON CONTRACT BASIS (Final Result Announced) ADVERTISEMENT NO : CRPD/RS/2024-25/08 DOWNLOAD ADVERTISEMENT( Hindi / English ) FINAL RESULT (NEW) RECRUITMENT OF SPECIALIST CADRE OFFICERS ON CONTRACTUAL BASIS (Final Result Announced ) ADVERTISEMENT NO : CRPD/SCO/2024-25/06 DOWNLOAD ADVERTISEMENT( Hindi / English ) FINAL RESULT (NEW) RECRUITMENT OF SPECIALIST CADRE OFFICERS ON REGULAR BASIS (Final Result Announced ) ADVERTISEMENT NO : CRPD/SCO/2024-25/05 DOWNLOAD ADVER",
    "keywords": [
      "announced",
      "banking",
      "basis",
      "cadre",
      "contractual",
      "final",
      "officer",
      "recruitment",
      "regular",
      "result",
      "specialist"
    ]
  },
  {
    "title": "RECRUITMENT OF SPECIALIST CADRE OFFICER ON CONTRACTUAL BASIS (Final Result Announced)",
    "url": "/generated/posts/recruitment-of-specialist-cadre-officer-on-contractual-basis-final-result-announced-27b302ecd8.html",
    "category": "Banking Jobs",
    "department": "Banking",
    "state": "",
    "description": "RECRUITMENT OF SPECIALIST CADRE OFFICER ON CONTRACTUAL BASIS (Final Result Announced) ADVERTISEMENT NO : CRPD/SCO/2024-25/16 DOWNLOAD ADVERTISEMENT( Hindi / English ) CORRIGENDUM (New) FINAL RESULT (New) RECRUITMENTOF SPECIALIST CADRE OFFICERS ON CONTRACTUAL BASIS (Final Result Announced) ADVERTISEMENT NO : CRPD/SCO/2024-25/14 DOWNLOAD ADVERTISEMENT( Hindi / English ) FINAL RESULT (NEW) RECRUITMENT OF SPORTS PERSONS FOR 2024-25 (LIST OF CANDIDATES PROVISIONALLY SELECTED ANNOUNCED ) ADVERTISEMENT NO : CRPD/SPORTS 2024-25/07 DOWNLOAD ADVERTISEMENT( Hindi / English ) OFFICERS - LIST OF CANDIDATES PROVISIONALLY SELECTED (NEW) CLERICAL- LIST OF CANDIDATES PROVISIONALLY SELECTED (NEW) ENGAGEMENT O",
    "keywords": [
      "announced",
      "banking",
      "basis",
      "cadre",
      "contractual",
      "final",
      "officer",
      "recruitment",
      "result",
      "specialist"
    ]
  },
  {
    "title": "RECRUITMENT OF SPECIALIST CADRE OFFICER ON CONTRACTUAL BASIS (FINAL RESULT ANNOUNCED – “NO CANDIDATE FOUND SUITABLE FOR INTERVIEW”)",
    "url": "/generated/posts/recruitment-of-specialist-cadre-officer-on-contractual-basis-final-result-announced-no-candidate-found-suitable-for-interview-cce3b8bcbc.html",
    "category": "Banking Jobs",
    "department": "Banking",
    "state": "",
    "description": "RECRUITMENT OF SPECIALIST CADRE OFFICER ON CONTRACTUAL BASIS (FINAL RESULT ANNOUNCED – “NO CANDIDATE FOUND SUITABLE FOR INTERVIEW”) ADVERTISEMENT NO: CRPD/SCO/2024-25/30 DOWNLOAD ADVERTISEMENT( Hindi / English ) FINAL RESULT - NO CANDIDATE FOUND SUITABLE FOR INTERVIEW (NEW)",
    "keywords": [
      "announced",
      "banking",
      "basis",
      "cadre",
      "candidate",
      "contractual",
      "final",
      "for",
      "found",
      "interview",
      "officer",
      "recruitment",
      "result",
      "specialist",
      "suitable"
    ]
  },
  {
    "title": "RECRUITMENT OF PROBATIONARY OFFICERS (FINAL RESULT ANNOUNCED)",
    "url": "/generated/posts/recruitment-of-probationary-officers-final-result-announced-66773fbbe3.html",
    "category": "Banking Jobs",
    "department": "Banking",
    "state": "",
    "description": "RECRUITMENT OF PROBATIONARY OFFICERS (FINAL RESULT ANNOUNCED) ADVERTISEMENT NO: CRPD/PO/2025-26/04 DOWNLOAD ADVERTISEMENT( English / Hindi ) CORRIGENDUM PRELIMINARY EXAM RESULT MAIN EXAM RESULT FINAL RESULT (NEW) MARKS SECURED BY THE CANDIDATES (NEW) LETTER TO SUCCESSFUL CANDIDATES (NEW)",
    "keywords": [
      "announced",
      "banking",
      "final",
      "officers",
      "probationary",
      "recruitment",
      "result"
    ]
  },
  {
    "title": "Notice: Regarding joining date and allotment of districts and units of finally selected candidates.",
    "url": "/generated/posts/notice-regarding-joining-date-and-allotment-of-districts-and-units-of-finally-selected-candidates-8c0a109f46.html",
    "category": "Result",
    "department": "Government",
    "state": "",
    "description": "",
    "keywords": [
      "allotment",
      "and",
      "candidates",
      "date",
      "districts",
      "finally",
      "government",
      "joining",
      "notice",
      "regarding",
      "result",
      "selected",
      "units"
    ]
  },
  {
    "title": "Notice: Regarding DET (Driving Efficiency Test) and release of Admit Cards of Driver Constable in Bihar Police & Fireman Driver in Bihar Fire Services.",
    "url": "/generated/posts/notice-regarding-det-driving-efficiency-test-and-release-of-admit-cards-of-driver-constable-in-bihar-police-and-fireman-driver-in-f962fc2a79.html",
    "category": "Admit Card",
    "department": "Police",
    "state": "",
    "description": "",
    "keywords": [
      "admit",
      "and",
      "bihar",
      "card",
      "cards",
      "constable",
      "det",
      "driver",
      "driving",
      "efficiency",
      "fire",
      "fireman",
      "notice",
      "police",
      "regarding",
      "release",
      "services",
      "test"
    ]
  },
  {
    "title": "Notice regarding Score Card of Shorthand Skill Test and Objective Type Written Test for the post of Court Master (Shorthand)",
    "url": "/generated/posts/notice-regarding-score-card-of-shorthand-skill-test-and-objective-type-written-test-for-the-post-of-court-master-shorthand-ad35b70442.html",
    "category": "Result",
    "department": "Government",
    "state": "",
    "description": "",
    "keywords": [
      "and",
      "card",
      "court",
      "for",
      "government",
      "master",
      "notice",
      "objective",
      "post",
      "regarding",
      "result",
      "score",
      "shorthand",
      "skill",
      "test",
      "the",
      "type",
      "written"
    ]
  },
  {
    "title": "Notice regarding Score Card of Computer Based Objective Type Written Test for the post of Junior Court Assistant",
    "url": "/generated/posts/notice-regarding-score-card-of-computer-based-objective-type-written-test-for-the-post-of-junior-court-assistant-199e38321e.html",
    "category": "Result",
    "department": "Government",
    "state": "",
    "description": "",
    "keywords": [
      "assistant",
      "based",
      "card",
      "computer",
      "court",
      "for",
      "government",
      "junior",
      "notice",
      "objective",
      "post",
      "regarding",
      "result",
      "score",
      "test",
      "the",
      "type",
      "written"
    ]
  },
  {
    "title": "Notice regarding link for downloading Admit Card for the post of Junior Court Assistant",
    "url": "/generated/posts/notice-regarding-link-for-downloading-admit-card-for-the-post-of-junior-court-assistant-fe136edb36.html",
    "category": "Admit Card",
    "department": "Government",
    "state": "",
    "description": "",
    "keywords": [
      "admit",
      "assistant",
      "card",
      "court",
      "downloading",
      "for",
      "government",
      "junior",
      "link",
      "notice",
      "post",
      "regarding",
      "the"
    ]
  },
  {
    "title": "Notice regarding Admit Card for the post of Junior Court Assistant",
    "url": "/generated/posts/notice-regarding-admit-card-for-the-post-of-junior-court-assistant-48027e5e33.html",
    "category": "Admit Card",
    "department": "Government",
    "state": "",
    "description": "",
    "keywords": [
      "admit",
      "assistant",
      "card",
      "court",
      "for",
      "government",
      "junior",
      "notice",
      "post",
      "regarding",
      "the"
    ]
  },
  {
    "title": "Link to download Admit Card with centre details for Typing Speed Test for the post of Junior Court Assistant",
    "url": "/generated/posts/link-to-download-admit-card-with-centre-details-for-typing-speed-test-for-the-post-of-junior-court-assistant-1efcf8e25a.html",
    "category": "Admit Card",
    "department": "Government",
    "state": "",
    "description": "",
    "keywords": [
      "admit",
      "assistant",
      "card",
      "centre",
      "court",
      "details",
      "download",
      "for",
      "government",
      "junior",
      "link",
      "post",
      "speed",
      "test",
      "the",
      "typing",
      "with"
    ]
  },
  {
    "title": "Link to download admit card for the posts of Court Master Shorthand, Senior Personal Assistant and Personal Assistant",
    "url": "/generated/posts/link-to-download-admit-card-for-the-posts-of-court-master-shorthand-senior-personal-assistant-and-personal-assistant-c95404f798.html",
    "category": "Admit Card",
    "department": "Government",
    "state": "",
    "description": "",
    "keywords": [
      "admit",
      "and",
      "assistant",
      "card",
      "court",
      "download",
      "for",
      "government",
      "link",
      "master",
      "personal",
      "posts",
      "senior",
      "shorthand",
      "the"
    ]
  },
  {
    "title": "Link to download admit card for the post of Junior Court Attendant (cooking knowing)",
    "url": "/generated/posts/link-to-download-admit-card-for-the-post-of-junior-court-attendant-cooking-knowing-0e1bb21412.html",
    "category": "Admit Card",
    "department": "Government",
    "state": "",
    "description": "",
    "keywords": [
      "admit",
      "attendant",
      "card",
      "cooking",
      "court",
      "download",
      "for",
      "government",
      "junior",
      "knowing",
      "link",
      "post",
      "the"
    ]
  },
  {
    "title": "Link to download Admit Card for Descriptive Test for the post of Junior Court Assistant",
    "url": "/generated/posts/link-to-download-admit-card-for-descriptive-test-for-the-post-of-junior-court-assistant-3cf49b18af.html",
    "category": "Admit Card",
    "department": "Government",
    "state": "",
    "description": "",
    "keywords": [
      "admit",
      "assistant",
      "card",
      "court",
      "descriptive",
      "download",
      "for",
      "government",
      "junior",
      "link",
      "post",
      "test",
      "the"
    ]
  },
  {
    "title": "Invitation of objection to answer keys of question paper of Written Test for the post of Junior Court Attendant (cooking knowing)",
    "url": "/generated/posts/invitation-of-objection-to-answer-keys-of-question-paper-of-written-test-for-the-post-of-junior-court-attendant-cooking-knowing-af57d01bef.html",
    "category": "Answer Key",
    "department": "Government",
    "state": "",
    "description": "",
    "keywords": [
      "answer",
      "attendant",
      "cooking",
      "court",
      "for",
      "government",
      "invitation",
      "junior",
      "key",
      "keys",
      "knowing",
      "objection",
      "paper",
      "post",
      "question",
      "test",
      "the",
      "written"
    ]
  },
  {
    "title": "In re.: Law Clerks-cum-Research Associates Examination, 2026.",
    "url": "/generated/posts/in-re-law-clerks-cum-research-associates-examination-2026-2d29a1ee53.html",
    "category": "Exam",
    "department": "Government",
    "state": "",
    "description": "",
    "keywords": [
      "2026",
      "associates",
      "clerkscumresearch",
      "exam",
      "examination",
      "government",
      "law"
    ]
  },
  {
    "title": "Important Notice: Supplementary Result for selection of Sri Ajay Newar for the post of Constable in Bihar Police.",
    "url": "/generated/posts/important-notice-supplementary-result-for-selection-of-sri-ajay-newar-for-the-post-of-constable-in-bihar-police-a225edef35.html",
    "category": "Recruitment",
    "department": "Police",
    "state": "",
    "description": "",
    "keywords": [
      "ajay",
      "bihar",
      "constable",
      "for",
      "important",
      "newar",
      "notice",
      "police",
      "post",
      "recruitment",
      "result",
      "selection",
      "sri",
      "supplementary",
      "the"
    ]
  },
  {
    "title": "Important Notice: Regarding Written Examination e-Admit-Card for the Post of Driver Constable in Bihar Police.",
    "url": "/generated/posts/important-notice-regarding-written-examination-e-admit-card-for-the-post-of-driver-constable-in-bihar-police-82d9dd25c5.html",
    "category": "Admit Card",
    "department": "Police",
    "state": "",
    "description": "",
    "keywords": [
      "admit",
      "bihar",
      "card",
      "constable",
      "driver",
      "eadmitcard",
      "examination",
      "for",
      "important",
      "notice",
      "police",
      "post",
      "regarding",
      "the",
      "written"
    ]
  },
  {
    "title": "Important Notice: Regarding Written Examination and e-Admit-Card for the Post of Driver Constable in Bihar Police.",
    "url": "/generated/posts/important-notice-regarding-written-examination-and-e-admit-card-for-the-post-of-driver-constable-in-bihar-police-956fd25544.html",
    "category": "Admit Card",
    "department": "Police",
    "state": "",
    "description": "",
    "keywords": [
      "admit",
      "and",
      "bihar",
      "card",
      "constable",
      "driver",
      "eadmitcard",
      "examination",
      "for",
      "important",
      "notice",
      "police",
      "post",
      "regarding",
      "the",
      "written"
    ]
  },
  {
    "title": "Important Notice: Regarding Written Examination & e-Admit Card for the Post of Constable (Operator) in Bihar Police.",
    "url": "/generated/posts/important-notice-regarding-written-examination-and-e-admit-card-for-the-post-of-constable-operator-in-bihar-police-21c93b393e.html",
    "category": "Admit Card",
    "department": "Police",
    "state": "",
    "description": "",
    "keywords": [
      "admit",
      "bihar",
      "card",
      "constable",
      "eadmit",
      "examination",
      "for",
      "important",
      "notice",
      "operator",
      "police",
      "post",
      "regarding",
      "the",
      "written"
    ]
  },
  {
    "title": "Important Notice: Regarding Written Examination & e-Admit Card for the Post of Constable (General Duty Close Cadre) in Special Branch of Bihar Police.",
    "url": "/generated/posts/important-notice-regarding-written-examination-and-e-admit-card-for-the-post-of-constable-general-duty-close-cadre-in-special-bran-6a14c21fc0.html",
    "category": "Admit Card",
    "department": "Police",
    "state": "",
    "description": "",
    "keywords": [
      "admit",
      "bihar",
      "branch",
      "cadre",
      "card",
      "close",
      "constable",
      "duty",
      "eadmit",
      "examination",
      "for",
      "general",
      "important",
      "notice",
      "police",
      "post",
      "regarding",
      "special",
      "the",
      "written"
    ]
  },
  {
    "title": "Important Notice: Regarding PET date and release of e-Admit Cards for Driver Constable in Bihar Police & Fireman Driver in Bihar Fire Services.",
    "url": "/generated/posts/important-notice-regarding-pet-date-and-release-of-e-admit-cards-for-driver-constable-in-bihar-police-and-fireman-driver-in-bihar-7fe6ace743.html",
    "category": "Admit Card",
    "department": "Police",
    "state": "",
    "description": "",
    "keywords": [
      "admit",
      "and",
      "bihar",
      "card",
      "cards",
      "constable",
      "date",
      "driver",
      "eadmit",
      "fire",
      "fireman",
      "for",
      "important",
      "notice",
      "pet",
      "police",
      "regarding",
      "release",
      "services"
    ]
  },
  {
    "title": "Important Notice: Regarding Exam Date & Release of e-Admit Card for Driver Constable in Bihar Police.",
    "url": "/generated/posts/important-notice-regarding-exam-date-and-release-of-e-admit-card-for-driver-constable-in-bihar-police-9566f93ad9.html",
    "category": "Admit Card",
    "department": "Police",
    "state": "",
    "description": "",
    "keywords": [
      "admit",
      "bihar",
      "card",
      "constable",
      "date",
      "driver",
      "eadmit",
      "exam",
      "for",
      "important",
      "notice",
      "police",
      "regarding",
      "release"
    ]
  },
  {
    "title": "Important Notice: Regarding Date of Joining and Allotment of Districts/Units to finally selected candidates as Constables in Bihar Police.",
    "url": "/generated/posts/important-notice-regarding-date-of-joining-and-allotment-of-districts-units-to-finally-selected-candidates-as-constables-in-bihar-49a4a29ccc.html",
    "category": "Result",
    "department": "Police",
    "state": "",
    "description": "",
    "keywords": [
      "allotment",
      "and",
      "bihar",
      "candidates",
      "constables",
      "date",
      "districtsunits",
      "finally",
      "important",
      "joining",
      "notice",
      "police",
      "regarding",
      "result",
      "selected"
    ]
  },
  {
    "title": "Important Notice: Regarding Date of Exam and release of Admit Card for Constable in Bihar Police.",
    "url": "/generated/posts/important-notice-regarding-date-of-exam-and-release-of-admit-card-for-constable-in-bihar-police-c26cc46ef9.html",
    "category": "Admit Card",
    "department": "Police",
    "state": "",
    "description": "",
    "keywords": [
      "admit",
      "and",
      "bihar",
      "card",
      "constable",
      "date",
      "exam",
      "for",
      "important",
      "notice",
      "police",
      "regarding",
      "release"
    ]
  },
  {
    "title": "Important Notice: Regarding Confirmation of Selection of Candidates, who were Provisionally Selected in Final Results Published on 27.05.2026.",
    "url": "/generated/posts/important-notice-regarding-confirmation-of-selection-of-candidates-who-were-provisionally-selected-in-final-results-published-on-2-3b27bdb8ed.html",
    "category": "Result",
    "department": "Government",
    "state": "",
    "description": "",
    "keywords": [
      "2026",
      "27052026",
      "candidates",
      "confirmation",
      "final",
      "government",
      "important",
      "notice",
      "provisionally",
      "published",
      "regarding",
      "result",
      "results",
      "selected",
      "selection",
      "were",
      "who"
    ]
  },
  {
    "title": "Important Notice: Regarding Change in Date of Written Examination & e-Admit Card for the Post of Constable (Operator) in Bihar Police.",
    "url": "/generated/posts/important-notice-regarding-change-in-date-of-written-examination-and-e-admit-card-for-the-post-of-constable-operator-in-bihar-poli-a947d7dee3.html",
    "category": "Admit Card",
    "department": "Police",
    "state": "",
    "description": "",
    "keywords": [
      "admit",
      "bihar",
      "card",
      "change",
      "constable",
      "date",
      "eadmit",
      "examination",
      "for",
      "important",
      "notice",
      "operator",
      "police",
      "post",
      "regarding",
      "the",
      "written"
    ]
  },
  {
    "title": "Important Notice: Regarding Applications Received from Candidates, Placed Below the Merit List, for the Preparation of a Waiting List or Reconsideration of Their Selection.",
    "url": "/generated/posts/important-notice-regarding-applications-received-from-candidates-placed-below-the-merit-list-for-the-preparation-of-a-waiting-list-06cda0ad87.html",
    "category": "Result",
    "department": "Government",
    "state": "",
    "description": "",
    "keywords": [
      "applications",
      "below",
      "candidates",
      "for",
      "from",
      "government",
      "important",
      "list",
      "merit",
      "notice",
      "placed",
      "preparation",
      "received",
      "reconsideration",
      "regarding",
      "result",
      "selection",
      "the",
      "their",
      "waiting"
    ]
  },
  {
    "title": "Important Notice: Regarding Application Submitted by the Candidates after Publication of Written Exam Results of Constable in Bihar Police",
    "url": "/generated/posts/important-notice-regarding-application-submitted-by-the-candidates-after-publication-of-written-exam-results-of-constable-in-bihar-9bceddbad6.html",
    "category": "Result",
    "department": "Police",
    "state": "",
    "description": "",
    "keywords": [
      "after",
      "application",
      "bihar",
      "candidates",
      "constable",
      "exam",
      "important",
      "notice",
      "police",
      "publication",
      "regarding",
      "result",
      "results",
      "submitted",
      "the",
      "written"
    ]
  },
  {
    "title": "Important Notice: Download e-Admit-Card of Physical Efficiency Test (PET) for the Post of Driver Constable in Bihar Police.",
    "url": "/generated/posts/important-notice-download-e-admit-card-of-physical-efficiency-test-pet-for-the-post-of-driver-constable-in-bihar-police-d91249bd74.html",
    "category": "Admit Card",
    "department": "Police",
    "state": "",
    "description": "",
    "keywords": [
      "admit",
      "bihar",
      "card",
      "constable",
      "download",
      "driver",
      "eadmitcard",
      "efficiency",
      "for",
      "important",
      "notice",
      "pet",
      "physical",
      "police",
      "post",
      "test",
      "the"
    ]
  },
  {
    "title": "Important Notice: Download e-Admit-Card of Physical Efficiency Test (PET) for the Post of Constable in Bihar Police.",
    "url": "/generated/posts/important-notice-download-e-admit-card-of-physical-efficiency-test-pet-for-the-post-of-constable-in-bihar-police-2a6a1276e5.html",
    "category": "Admit Card",
    "department": "Police",
    "state": "",
    "description": "",
    "keywords": [
      "admit",
      "bihar",
      "card",
      "constable",
      "download",
      "eadmitcard",
      "efficiency",
      "for",
      "important",
      "notice",
      "pet",
      "physical",
      "police",
      "post",
      "test",
      "the"
    ]
  },
  {
    "title": "Important Notice: Download e-Admit-Card of Driving Efficiency Test (DET) for the Post of Driver Constable in Bihar Police.",
    "url": "/generated/posts/important-notice-download-e-admit-card-of-driving-efficiency-test-det-for-the-post-of-driver-constable-in-bihar-police-a37b2960f4.html",
    "category": "Admit Card",
    "department": "Police",
    "state": "",
    "description": "",
    "keywords": [
      "admit",
      "bihar",
      "card",
      "constable",
      "det",
      "download",
      "driver",
      "driving",
      "eadmitcard",
      "efficiency",
      "for",
      "important",
      "notice",
      "police",
      "post",
      "test",
      "the"
    ]
  },
  {
    "title": "ENGAGEMENT OF SPECIALIST CADRE OFFICERS ON CONTRACTUAL BASIS (FINAL RESULT ANNOUNCED FOR VARIOUS POSTS)",
    "url": "/generated/posts/engagement-of-specialist-cadre-officers-on-contractual-basis-final-result-announced-for-various-posts-e26e608844.html",
    "category": "Banking Jobs",
    "department": "Banking",
    "state": "",
    "description": "ENGAGEMENT OF SPECIALIST CADRE OFFICERS ON CONTRACTUAL BASIS (FINAL RESULT ANNOUNCED FOR VARIOUS POSTS) ADVERTISEMENT NO: CRPD/SCO/2024-25/20 DOWNLOAD ADVERTISEMENT( Hindi / English ) FINAL RESULT - CENTRAL RESEARCH TEAM (PRODUCT LEAD) (NEW) FINAL RESULT - RELATIONSHIP MANAGER TEAM LEAD (NEW) FINAL RESULT – REGIONAL HEAD (NEW) CANCELLATION OF RECRUITMENT PROCESS FOR THE POST OF HEAD (PRODUCT, INVESTMENT & RESEARCH) AND ZONAL HEAD (NEW)",
    "keywords": [
      "announced",
      "banking",
      "basis",
      "cadre",
      "contractual",
      "engagement",
      "final",
      "for",
      "officers",
      "posts",
      "recruitment",
      "result",
      "specialist",
      "various"
    ]
  },
  {
    "title": "ENGAGEMENT OF SPECIALIST CADRE OFFICERS ON CONTRACT BASIS FOR SBI WEALTH MANAGEMENT (FINAL RESULT ANNOUNCED)",
    "url": "/generated/posts/engagement-of-specialist-cadre-officers-on-contract-basis-for-sbi-wealth-management-final-result-announced-f6c4714f1f.html",
    "category": "Banking Jobs",
    "department": "Banking",
    "state": "",
    "description": "ENGAGEMENT OF SPECIALIST CADRE OFFICERS ON CONTRACT BASIS FOR SBI WEALTH MANAGEMENT (FINAL RESULT ANNOUNCED) ADVERTISEMENT NO : CRPD/SCO/2024-25/09 DOWNLOAD ADVERTISEMENT( Hindi / English ) FINAL RESULT CENTRAL RESEARCH TEAM (PRODUCT LEAD),CENTRAL RESEARCH TEAM (SUPPORT),INVESTMENT OFFICER,INVESTMENT SPECIALIST,PROJECT DEVELOPMENT MANAGER (BUSINESS),PROJECT DEVELOPMENT MANAGER (TECHNOLOGY),REGIONAL HEAD,RELATIONSHIP MANAGER TEAM LEAD,VP WEALTH (NEW) RELATIONSHIP MANAGER (NEW) ENGAGEMENT OF SPECIALIST CADRE OFFICER ON CONTRACT BASIS (Final Result Announced ) ADVERTISEMENT NO : CRPD/SCO/2024-25/12 DOWNLOAD ADVERTISEMENT( Hindi / English ) FINAL RESULT (NEW) ENGAGEMENT OF SPECIALIST CADRE OFFIC",
    "keywords": [
      "announced",
      "banking",
      "basis",
      "cadre",
      "contract",
      "engagement",
      "final",
      "for",
      "management",
      "officers",
      "recruitment",
      "result",
      "sbi",
      "specialist",
      "wealth"
    ]
  },
  {
    "title": "ENGAGEMENT OF SPECIALIST CADRE OFFICERS ON CONTRACT BASIS (FINAL RESULT ANNOUNCED FOR THE POST OF INVESTMENT SPECIALIST, INVESTMENT OFFICER & RELATIONSHIP MANAGER TEAM LEAD)",
    "url": "/generated/posts/engagement-of-specialist-cadre-officers-on-contract-basis-final-result-announced-for-the-post-of-investment-specialist-investment-a28a651341.html",
    "category": "Banking Jobs",
    "department": "Banking",
    "state": "",
    "description": "ENGAGEMENT OF SPECIALIST CADRE OFFICERS ON CONTRACT BASIS (FINAL RESULT ANNOUNCED FOR THE POST OF INVESTMENT SPECIALIST, INVESTMENT OFFICER & RELATIONSHIP MANAGER TEAM LEAD) ADVERTISEMENT NO: CRPD/SCO/2025-26/15 DOWNLOAD ADVERTISEMENT( Hindi / English ) HEAD (PRODUCT, INVESTMENT RESEARCH) - LIST OF CANDIDATES PROVISIONALLY SELECTED ANNOUNCED (NEW) ZONAL HEAD (RETAIL) - LIST OF CANDIDATES PROVISIONALLY SELECTED ANNOUNCED (NEW) PROJECT DEVELOPMENT MANAGER (BUSINESS) - LIST OF CANDIDATES PROVISIONALLY SELECTED ANNOUNCED (NEW) REGIONAL HEAD - LIST OF CANDIDATES PROVISIONALLY SELECTED ANNOUNCED (NEW) CENTRAL RESEARCH TEAM (SUPPORT) - LIST OF CANDIDATES PROVISIONALLY SELECTED ANNOUNCED (NEW) INVES",
    "keywords": [
      "announced",
      "banking",
      "basis",
      "cadre",
      "contract",
      "engagement",
      "final",
      "for",
      "investment",
      "lead",
      "manager",
      "officer",
      "officers",
      "post",
      "recruitment",
      "relationship",
      "result",
      "specialist",
      "team",
      "the"
    ]
  },
  {
    "title": "ENGAGEMENT OF SPECIALIST CADRE OFFICER ON CONTRACTUAL BASIS (Final Result Announced )",
    "url": "/generated/posts/engagement-of-specialist-cadre-officer-on-contractual-basis-final-result-announced-5486fb580f.html",
    "category": "Banking Jobs",
    "department": "Banking",
    "state": "",
    "description": "ENGAGEMENT OF SPECIALIST CADRE OFFICER ON CONTRACTUAL BASIS (Final Result Announced ) ADVERTISEMENT NO : CRPD/SCO/2024-25/13 DOWNLOAD ADVERTISEMENT( Hindi / English ) FINAL RESULT (NEW) RECRUITMENT OF SPECIALIST CADRE OFFICERS ON REGULAR BASIS (Final Result Announced ) ADVERTISEMENT NO : CRPD/SCO/2024-25/11 DOWNLOAD ADVERTISEMENT( Hindi / English ) FINAL RESULT (NEW) RECRUITMENT OF SPECIALIST CADRE OFFICER ON REGULAR & CONTRACTUAL BASIS (Final Result Announced ) ADVERTISEMENT NO : CRPD/SCO/2024-25/10 DOWNLOAD ADVERTISEMENT( Hindi / English ) FINAL RESULT (NEW) ENGAGEMENT OF RETIRED BANK OFFICERS ON CONTRACT BASIS (Final Result Announced) ADVERTISEMENT NO : CRPD/RS/2024-25/08 DOWNLOAD ADVERTI",
    "keywords": [
      "announced",
      "banking",
      "basis",
      "cadre",
      "contractual",
      "engagement",
      "final",
      "officer",
      "recruitment",
      "result",
      "specialist"
    ]
  },
  {
    "title": "ENGAGEMENT OF SPECIALIST CADRE OFFICER ON CONTRACT BASIS (Final Result Announced )",
    "url": "/generated/posts/engagement-of-specialist-cadre-officer-on-contract-basis-final-result-announced-76e83f4b3d.html",
    "category": "Banking Jobs",
    "department": "Banking",
    "state": "",
    "description": "ENGAGEMENT OF SPECIALIST CADRE OFFICER ON CONTRACT BASIS (Final Result Announced ) ADVERTISEMENT NO : CRPD/SCO/2024-25/12 DOWNLOAD ADVERTISEMENT( Hindi / English ) FINAL RESULT (NEW) ENGAGEMENT OF SPECIALIST CADRE OFFICER ON CONTRACTUAL BASIS (Final Result Announced ) ADVERTISEMENT NO : CRPD/SCO/2024-25/13 DOWNLOAD ADVERTISEMENT( Hindi / English ) FINAL RESULT (NEW) RECRUITMENT OF SPECIALIST CADRE OFFICERS ON REGULAR BASIS (Final Result Announced ) ADVERTISEMENT NO : CRPD/SCO/2024-25/11 DOWNLOAD ADVERTISEMENT( Hindi / English ) FINAL RESULT (NEW) RECRUITMENT OF SPECIALIST CADRE OFFICER ON REGULAR & CONTRACTUAL BASIS (Final Result Announced ) ADVERTISEMENT NO : CRPD/SCO/2024-25/10 DOWNLOAD AD",
    "keywords": [
      "announced",
      "banking",
      "basis",
      "cadre",
      "contract",
      "engagement",
      "final",
      "officer",
      "recruitment",
      "result",
      "specialist"
    ]
  },
  {
    "title": "ENGAGEMENT OF RETIRED BANK OFFICERS ON CONTRACT BASIS (Final Result Announced)",
    "url": "/generated/posts/engagement-of-retired-bank-officers-on-contract-basis-final-result-announced-b8eb8589dc.html",
    "category": "Banking Jobs",
    "department": "Banking",
    "state": "",
    "description": "ENGAGEMENT OF RETIRED BANK OFFICERS ON CONTRACT BASIS (Final Result Announced) ADVERTISEMENT NO : CRPD/RS/2024-25/08 DOWNLOAD ADVERTISEMENT( Hindi / English ) FINAL RESULT (NEW) RECRUITMENT OF SPECIALIST CADRE OFFICERS ON CONTRACTUAL BASIS (Final Result Announced ) ADVERTISEMENT NO : CRPD/SCO/2024-25/06 DOWNLOAD ADVERTISEMENT( Hindi / English ) FINAL RESULT (NEW) RECRUITMENT OF SPECIALIST CADRE OFFICERS ON REGULAR BASIS (Final Result Announced ) ADVERTISEMENT NO : CRPD/SCO/2024-25/05 DOWNLOAD ADVERTISEMENT( Hindi / English ) FINAL RESULT (NEW) RECRUITMENT OF SPECIALIST CADRE OFFICERS ON REGULAR BASIS (FINAL RESULT ANNOUNCED ) ADVERTISEMENT NO : CRPD/SCO/2024-25/04 DOWNLOAD ADVERTISEMENT( Hin",
    "keywords": [
      "announced",
      "bank",
      "banking",
      "basis",
      "contract",
      "engagement",
      "final",
      "officers",
      "recruitment",
      "result",
      "retired"
    ]
  },
  {
    "title": "Employment Notification No. 2025/05(J) – DOWNLOAD CALL LETTER FOR DOCUMENT VERIFICATION / ADMIT CARD FOR TRADE TEST SCHEDULED ON 21, 22 & 25 FEBRUARY 2026",
    "url": "/generated/posts/employment-notification-no-2025-05-j-download-call-letter-for-document-verification-admit-card-for-trade-test-scheduled-on-21-22-a-362c455c12.html",
    "category": "Admit Card",
    "department": "Banking",
    "state": "",
    "description": "Current Job Openings Engagement of Apprentices and Trainee Other Positions 1. RECRUITMENT OF OFFICERS [EMPLOYMENT NOTIFICATION -2026/04(O)] GRSE Employment Notification No. 2026/04(O) (Detailed Notification) ( | PDF | 1.1 KB | English) GRSE Employment Notification No. 2026/04(O) (Abridged Notification-English) ( | PDF | 717 KB | English) GRSE Employment Notification No. 2026/04(O) (Abridged Notification-Hindi) ( | PDF | 631 KB | Hindi) Opening date for Online Registration : Opening date for Onli",
    "keywords": [
      "2025",
      "202505j",
      "2026",
      "admit",
      "banking",
      "call",
      "card",
      "document",
      "download",
      "employment",
      "february",
      "for",
      "letter",
      "notification",
      "scheduled",
      "test",
      "trade",
      "verification"
    ]
  },
  {
    "title": "Corrigendum Letter: Regarding result of Written Examination for the post of Driver Constable in Bihar Police.",
    "url": "/generated/posts/corrigendum-letter-regarding-result-of-written-examination-for-the-post-of-driver-constable-in-bihar-police-559d7c1da3.html",
    "category": "Result",
    "department": "Police",
    "state": "",
    "description": "",
    "keywords": [
      "bihar",
      "constable",
      "corrigendum",
      "driver",
      "examination",
      "for",
      "letter",
      "police",
      "post",
      "regarding",
      "result",
      "the",
      "written"
    ]
  },
  {
    "title": "Consolidated result of Written Test and Computer Knowledge Test for the post of Additional Registrar (Housekeeping) (Ex-cadre)",
    "url": "/generated/posts/consolidated-result-of-written-test-and-computer-knowledge-test-for-the-post-of-additional-registrar-housekeeping-ex-cadre-6632e85d03.html",
    "category": "Result",
    "department": "Government",
    "state": "",
    "description": "",
    "keywords": [
      "additional",
      "and",
      "computer",
      "consolidated",
      "excadre",
      "for",
      "government",
      "housekeeping",
      "knowledge",
      "post",
      "registrar",
      "result",
      "test",
      "the",
      "written"
    ]
  },
  {
    "title": "Consolidated result of Objective Type Written and Computer Knowledge Tests, Shorthand Skill Test and Typing Speed Test on Computer for the post of Senior Personal Assistant",
    "url": "/generated/posts/consolidated-result-of-objective-type-written-and-computer-knowledge-tests-shorthand-skill-test-and-typing-speed-test-on-computer-cb19242448.html",
    "category": "Result",
    "department": "Government",
    "state": "",
    "description": "",
    "keywords": [
      "and",
      "assistant",
      "computer",
      "consolidated",
      "for",
      "government",
      "knowledge",
      "objective",
      "personal",
      "post",
      "result",
      "senior",
      "shorthand",
      "skill",
      "speed",
      "test",
      "tests",
      "the",
      "type",
      "typing",
      "written"
    ]
  },
  {
    "title": "Consolidated result of Objective Type Written and Computer Knowledge Tests, Shorthand Skill Test and Typing Speed Test on Computer for the post of Personal Assistant",
    "url": "/generated/posts/consolidated-result-of-objective-type-written-and-computer-knowledge-tests-shorthand-skill-test-and-typing-speed-test-on-computer-c1d0d2fd25.html",
    "category": "Result",
    "department": "Government",
    "state": "",
    "description": "",
    "keywords": [
      "and",
      "assistant",
      "computer",
      "consolidated",
      "for",
      "government",
      "knowledge",
      "objective",
      "personal",
      "post",
      "result",
      "shorthand",
      "skill",
      "speed",
      "test",
      "tests",
      "the",
      "type",
      "typing",
      "written"
    ]
  },
  {
    "title": "Selection List - Sports Officer Exam 2024, Dated 22/08/2026",
    "url": "/generated/posts/selection-list-sports-officer-exam-2024-dated-22-08-2026-ce992870de.html",
    "category": "Result",
    "department": "MPPSC",
    "state": "",
    "description": "",
    "keywords": [
      "2024",
      "22082026",
      "dated",
      "exam",
      "list",
      "mppsc",
      "officer",
      "result",
      "selection",
      "sports"
    ]
  },
  {
    "title": "Obtained Mark List - Sports Officer Exam 2024, Dated 22/08/2026",
    "url": "/generated/posts/obtained-mark-list-sports-officer-exam-2024-dated-22-08-2026-5180a5e2c1.html",
    "category": "Exam",
    "department": "MPPSC",
    "state": "",
    "description": "",
    "keywords": [
      "2024",
      "22082026",
      "dated",
      "exam",
      "list",
      "mark",
      "mppsc",
      "obtained",
      "officer",
      "sports"
    ]
  },
  {
    "title": "Caveat Vigyapti on Selection List of Sports Officer Exam 2024, Dated 22/08/2026",
    "url": "/generated/posts/caveat-vigyapti-on-selection-list-of-sports-officer-exam-2024-dated-22-08-2026-c741b1b282.html",
    "category": "Result",
    "department": "MPPSC",
    "state": "",
    "description": "",
    "keywords": [
      "2024",
      "22082026",
      "caveat",
      "dated",
      "exam",
      "list",
      "mppsc",
      "officer",
      "result",
      "selection",
      "sports",
      "vigyapti"
    ]
  },
  {
    "title": "IIFCL Direct Recruitment for the Post AGM (Grade ‘C’ Officer) Registration From 19-Aug-2026",
    "url": "/generated/posts/iifcl-direct-recruitment-for-the-post-agm-grade-c-officer-registration-from-19-aug-2026-38440c0587.html",
    "category": "Banking Jobs",
    "department": "IBPS",
    "state": "",
    "description": "Direct Recruitment for the Post Assistant General Manager (Grade ‘C’ Officer) On Regular Basis at IIFCL Important Events Dates Commencement of online registration of application 19/08/2026 Closure of registration of application 25/08/2026 Closure for editing application details 25/08/2026 Last date for printing your application 09/09/2026 Online Application validation rules and design are based on the Notification requirement. Candidates are advised to read the notification carefully and refer \"How to Apply\" & \"FAQ\" pages on the main page. Application submitted through Online form does not imply that candidate has fulfilled all the criteria given in the notification. Application is subject t",
    "keywords": [
      "19aug2026",
      "2026",
      "agm",
      "direct",
      "for",
      "from",
      "grade",
      "ibps",
      "iifcl",
      "officer",
      "post",
      "recruitment",
      "registration",
      "the"
    ]
  },
  {
    "title": "Online Preliminary Exam Call Letter for CRP PO/MT XVI Probationary Officers / Management Trainees",
    "url": "/generated/posts/online-preliminary-exam-call-letter-for-crp-po-mt-xvi-probationary-officers-management-trainees-057a0b78a1.html",
    "category": "Banking Jobs",
    "department": "IBPS",
    "state": "",
    "description": "",
    "keywords": [
      "call",
      "crp",
      "exam",
      "for",
      "government",
      "jobs",
      "latest",
      "letter",
      "management",
      "officers",
      "online",
      "pomt",
      "preliminary",
      "probationary",
      "trainees",
      "xvi"
    ]
  },
  {
    "title": "परीक्षा कार्यक्रम",
    "url": "/generated/posts/exam-0a5e8290a4.html",
    "category": "Uttarakhand Jobs",
    "department": "Government",
    "state": "",
    "description": "ीक्षा कार्यक्रम(UPDATED EXAM CALENDAR) | Uttarakhand Subordinate Service Selection Commission | India Search Search Size Increase Font Size Decrease Normal Font Tex",
    "keywords": [
      "government",
      "jobs",
      "latest",
      "new"
    ]
  },
  {
    "title": "पदनाम विधि सहायक/शोध अधिकारी/सहायक बोरिंग टेक्नीशियन व अन्य तकनीकी अर्हता से सम्बंधित पाठ्यक्रम",
    "url": "/generated/posts/syllabus-16e1f03edf.html",
    "category": "Uttarakhand Jobs",
    "department": "Government",
    "state": "",
    "description": "ाम-विधि सहायक/शोध अधिकारी/सहायक बोरिंग टेक्नीशियन व अन्य तकनीकी अर्हता से सम्बंधित पाठ्यक्रम(Syllabus) | Uttarakhand Subordinate Service Selection Commission | India Search Search",
    "keywords": [
      "government",
      "jobs",
      "latest",
      "new"
    ]
  },
  {
    "title": "पदनाम पटवारी/लेखपाल) की शारीरिक मानक एवं दक्षता परीक्षा के प्रवेश पत्र",
    "url": "/generated/posts/exam-admit-card-778be8e994.html",
    "category": "Uttarakhand Jobs",
    "department": "UKSSSC",
    "state": "",
    "description": ", Father's Name and Date of birth Login with Mobile No. and Date of birth © Uttarakhand Subord",
    "keywords": [
      "government",
      "jobs",
      "latest"
    ]
  },
  {
    "title": "TERM END EXAMINATION- AUGUST 2026 TIME TABLE",
    "url": "/generated/posts/term-end-examination-august-2026-time-table-b0e5b43852.html",
    "category": "Exam",
    "department": "Government",
    "state": "",
    "description": "+ All and Ever NAAC 'A+' Grade with CGPA 3.32 (Cycle - 1) (A State Open University established by the Tamil Nadu Government , Recogni",
    "keywords": [
      "2026",
      "august",
      "end",
      "examination",
      "government",
      "jobs",
      "latest",
      "table",
      "term",
      "time"
    ]
  },
  {
    "title": "TERM END EXAMINATION AUGUST 2026 - Notification",
    "url": "/generated/posts/term-end-examination-august-2026-notification-9d79e3bc2a.html",
    "category": "Exam",
    "department": "Government",
    "state": "",
    "description": "",
    "keywords": [
      "2026",
      "august",
      "end",
      "examination",
      "government",
      "notification",
      "recruitment",
      "term"
    ]
  },
  {
    "title": "Result of University Entrance Test (UET-UG) – 2026",
    "url": "/generated/posts/result-of-university-entrance-test-uet-ug-2026-1f0825bb0a.html",
    "category": "Result",
    "department": "Government",
    "state": "",
    "description": "- SKUAST-Kashmir IUMS Admissions How it Works Programmes Sign In Form Filling Tutorial Important Facing difficulty in filling the application form? Watch the Step-by-Step Official Tutorial Video for Undergraduate (UG) Admissions! Watch Video Registrar's Advisory Kickstart your futur",
    "keywords": [
      "2026",
      "entrance",
      "government",
      "result",
      "test",
      "uetug",
      "university"
    ]
  },
  {
    "title": "RESULT Dated 23-07-2026: Marks obtained by the candidates in the Driving Test followed by Viva Voce for recruitment to the posts of Driver in the establishments of the District & Subordinate Judiciary of Tripura in pursuance of the Advertisement No. DC 01/2025, dated 23.05.2025.",
    "url": "/generated/posts/result-dated-23-07-2026-marks-obtained-by-the-candidates-in-the-driving-test-followed-by-viva-voce-for-recruitment-to-the-posts-of-dea9c6e48c.html",
    "category": "Result",
    "department": "Government",
    "state": "",
    "description": "",
    "keywords": [
      "012025",
      "2026",
      "23052025",
      "23072026",
      "advertisement",
      "candidates",
      "dated",
      "district",
      "driver",
      "driving",
      "establishments",
      "followed",
      "for",
      "government",
      "judiciary",
      "marks",
      "obtained",
      "posts",
      "pursuance",
      "recruitment",
      "result",
      "subordinate",
      "test",
      "the",
      "tripura",
      "viva",
      "voce"
    ]
  },
  {
    "title": "Notice: Use this link to download your e-Admit Card for Driving Efficiency Test (DET) to be conducted for the post of Bihar Police Driver Constable",
    "url": "/generated/posts/notice-use-this-link-to-download-your-e-admit-card-for-driving-efficiency-test-det-to-be-conducted-for-the-post-of-bihar-police-dr-4f8a057b39.html",
    "category": "Admit Card",
    "department": "Police",
    "state": "",
    "description": "",
    "keywords": [
      "admit",
      "banking",
      "bihar",
      "card",
      "conducted",
      "constable",
      "det",
      "download",
      "driver",
      "driving",
      "eadmit",
      "efficiency",
      "for",
      "link",
      "notice",
      "police",
      "post",
      "test",
      "the",
      "this",
      "use",
      "your"
    ]
  },
  {
    "title": "Important Notice: Download your e-Admit Card for PET of Bihar Police Driver Constable.",
    "url": "/generated/posts/important-notice-download-your-e-admit-card-for-pet-of-bihar-police-driver-constable-08699433b4.html",
    "category": "Admit Card",
    "department": "Police",
    "state": "",
    "description": "",
    "keywords": [
      "admit",
      "bihar",
      "card",
      "constable",
      "download",
      "driver",
      "eadmit",
      "for",
      "important",
      "notice",
      "pet",
      "police",
      "your"
    ]
  },
  {
    "title": "Important Notice: Download your e-Admit Card for PET of Bihar Police Constable.",
    "url": "/generated/posts/important-notice-download-your-e-admit-card-for-pet-of-bihar-police-constable-c3e64fbd75.html",
    "category": "Admit Card",
    "department": "Police",
    "state": "",
    "description": "",
    "keywords": [
      "admit",
      "bihar",
      "card",
      "constable",
      "download",
      "eadmit",
      "for",
      "important",
      "notice",
      "pet",
      "police",
      "your"
    ]
  },
  {
    "title": "Important Notice: Download Admit Card for PET of Bihar Police Constable",
    "url": "/generated/posts/important-notice-download-admit-card-for-pet-of-bihar-police-constable-bf7a6acbbe.html",
    "category": "Admit Card",
    "department": "Police",
    "state": "",
    "description": "",
    "keywords": [
      "admit",
      "bihar",
      "card",
      "constable",
      "download",
      "for",
      "important",
      "notice",
      "pet",
      "police"
    ]
  },
  {
    "title": "Final Scorecard and Portal Access for Professor/Chief Scientist",
    "url": "/generated/posts/final-scorecard-and-portal-access-for-professor-chief-scientist-53f933877a.html",
    "category": "Result",
    "department": "Teaching",
    "state": "",
    "description": "| Professor-cum-Chief Scientist | SKUAST-Kashmir Sher-E-Kashmir University of Agricultural Sciences & Technology of Kashmir Download Notice Sign in to your Account ! 3rd Best State Agri. Uni 7th NIRF Agri & Allied 36th State Public Univ. 75th University Category 94th Overall Categ",
    "keywords": [
      "access",
      "and",
      "final",
      "for",
      "jobs",
      "latest",
      "portal",
      "professorchief",
      "scientist",
      "scorecard",
      "teaching"
    ]
  },
  {
    "title": "Final Scorecard and Portal Access for Officer Recruitment",
    "url": "/generated/posts/final-scorecard-and-portal-access-for-officer-recruitment-c4b367a6c1.html",
    "category": "Result",
    "department": "Agriculture",
    "state": "",
    "description": "| SKUAST-Kashmir Sher-e-Kashmir University of Agricultural Sciences & Technology of Kashmir Main Campus, Shalimar, Srinagar - 190025 Login / View Score",
    "keywords": [
      "access",
      "and",
      "final",
      "for",
      "government",
      "officer",
      "portal",
      "recruitment",
      "scorecard"
    ]
  },
  {
    "title": "Exam Time Table",
    "url": "/generated/posts/exam-time-table-464c945bd1.html",
    "category": "Exam",
    "department": "Government",
    "state": "",
    "description": "+ All and Ever NAAC 'A+' Grade with CGPA 3.32 (Cycle - 1) (A State Open University established by the Tamil Nadu Government , Recogni",
    "keywords": [
      "exam",
      "government",
      "jobs",
      "latest",
      "table",
      "time"
    ]
  },
  {
    "title": "ENTRANCE EXAMINATION RESULT 2026 FOR all UG/PG/Ph.D. programmes",
    "url": "/generated/posts/entrance-examination-result-2026-for-all-ug-pg-ph-d-programmes-841282acda.html",
    "category": "Uttarakhand Jobs",
    "department": "Agriculture",
    "state": "",
    "description": "& TECHNOLOGY (Pantnagar, U.S. Nagar, Uttarakhand) Home Candidate Login for Counselling Sponsored MASTERS/M.Tech/Ph.D./Admission to the Second/Third Year for UG programmes under NEP2020 login ☰ Select your programme: Please Select UG MASTERS' MCA P",
    "keywords": [
      "2026",
      "all",
      "entrance",
      "examination",
      "for",
      "government",
      "programmes",
      "result",
      "ugpgphd"
    ]
  },
  {
    "title": "SBI Recruitment of Junior Associates Registration From 11-Aug-2026",
    "url": "/generated/posts/sbi-recruitment-of-junior-associates-registration-from-11-aug-2026-293ff763d9.html",
    "category": "Banking Jobs",
    "department": "IBPS",
    "state": "",
    "description": "Recruitment of Junior Associates (Customer Support & Sales) (Advertisement No. CRPD/CR/2026-27/17) Important Events Dates Commencement of online registration of application 11/08/2026 Closure of registration of application 31/08/2026 Closure for editing application details 31/08/2026 Last date for printing your application 15/09/2026 Online Fee Payment 11/08/2026 to 31/08/2026 Online Application validation rules and design are based on the Notification requirement. Candidates are advised to read the notification carefully and refer \"How to Apply\" & \"FAQ\" pages on the main page. Application submitted through Online form does not imply that candidate has fulfilled all the criteria given in the",
    "keywords": [
      "11aug2026",
      "2026",
      "associates",
      "from",
      "ibps",
      "junior",
      "recruitment",
      "registration",
      "sbi"
    ]
  },
  {
    "title": "SBI Recruitment of Junior Associates (Customer Support & Sales) Registration From 07-Aug-2026",
    "url": "/generated/posts/sbi-recruitment-of-junior-associates-customer-support-and-sales-registration-from-07-aug-2026-e77857a75a.html",
    "category": "Banking Jobs",
    "department": "IBPS",
    "state": "",
    "description": "Recruitment of Junior Associates (Customer Support & Sales) Special Recruitment Drive for SC/ST/OBC (Advertisement No. CRPD/CR/SPLDRIVE/2026-27/16) Important Events Dates Commencement of online registration of application 07/08/2026 Closure of registration of application 27/08/2026 Closure for editing application details 27/08/2026 Last date for printing your application 11/09/2026 Online Fee Payment 07/08/2026 to 27/08/2026 Online Application validation rules and design are based on the Notification requirement. Candidates are advised to read the notification carefully and refer \"How to Apply\" & \"FAQ\" pages on the main page. Application submitted through Online form does not imply that cand",
    "keywords": [
      "07aug2026",
      "2026",
      "associates",
      "customer",
      "from",
      "ibps",
      "junior",
      "recruitment",
      "registration",
      "sales",
      "sbi",
      "support"
    ]
  },
  {
    "title": "RECRUITMENT OF JUNIOR ASSOCIATES SPECIAL RECRUITMENT DRIVE FOR SC/ST/OBC BACKLOG VACANCIES (Apply Online from 07.08.2026 to 27.08.2026)",
    "url": "/generated/posts/recruitment-of-junior-associates-special-recruitment-drive-for-sc-st-obc-backlog-vacancies-apply-online-from-07-08-2026-to-27-08-2-296b53e481.html",
    "category": "Banking Jobs",
    "department": "Banking",
    "state": "",
    "description": "RECRUITMENT OF JUNIOR ASSOCIATES SPECIAL RECRUITMENT DRIVE FOR SC/ST/OBC BACKLOG VACANCIES (Apply Online from 07.08.2026 to 27.08.2026) ADVERTISEMENT NO: CRPD/CR/SPLDRIVE/2026-27/16 LAST DATE TO APPLY : 27-08-2026 DOWNLOAD ADVERTISEMENT (Hindi (592 KB) / English) (714 KB) (NEW) APPLY ONLINE (07.08.2026 to 27.08.2026) (NEW) Apply Now",
    "keywords": [
      "07082026",
      "2026",
      "27082026",
      "apply",
      "associates",
      "backlog",
      "banking",
      "drive",
      "for",
      "from",
      "junior",
      "online",
      "recruitment",
      "scstobc",
      "special",
      "vacancies"
    ]
  },
  {
    "title": "RECRUITMENT OF JUNIOR ASSOCIATES (CUSTOMER SUPPORT & SALES) (Apply Online from 11.08.2026 to 31.08.2026)",
    "url": "/generated/posts/recruitment-of-junior-associates-customer-support-and-sales-apply-online-from-11-08-2026-to-31-08-2026-d1bfc3d91f.html",
    "category": "Banking Jobs",
    "department": "Banking",
    "state": "",
    "description": "RECRUITMENT OF JUNIOR ASSOCIATES (CUSTOMER SUPPORT & SALES) (Apply Online from 11.08.2026 to 31.08.2026) ADVERTISEMENT NO: CRPD/CR/2026-27/17 LAST DATE TO APPLY : 31-08-2026 DOWNLOAD ADVERTISEMENT( HINDI (645 KB) / English) (959 KB) (NEW) APPLY ONLINE (11.08.2026 to 31.08.2026) (NEW) Apply Now",
    "keywords": [
      "11082026",
      "2026",
      "31082026",
      "apply",
      "associates",
      "banking",
      "customer",
      "from",
      "junior",
      "online",
      "recruitment",
      "sales",
      "support"
    ]
  }
];